<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Errors</title>
    <script data-main="js/setup" src="js/require.js"></script>
    <link rel="stylesheet" href="fonts/fonts.css" />
    <link rel="stylesheet" href="fonts/fontawesome-all.min.css" />
    <link rel="stylesheet" href="css/layout.css" />
    <link rel="stylesheet" href="toc/themes/default/style.min.css" />
    <link rel="stylesheet" href="css/design.css" />
  </head>
  <body>

  <div id="control-panel">
    <div id="control-strip-m">
      <div id="control-strip-m-find"><div id="m-find"></div></div>
      <div id="control-strip-m-toc"><div id="m-toc"></div></div>
    </div>
    <div id="controls">
      <div id="control-find">
        <div id="control-find-content"><input id="find" class="typeahead" placeholder="Find something..."></div>
      </div>
      <div id="control-toc">
        <div id="control-toc-content"><div id="toc"></div></div>
      </div>
    </div>
  </div>
  <div id="control-strip-w">
    <div id="control-strip-w-find"></div>
    <div id="control-strip-w-toc"></div>
  </div>

  <div id="content">

  
<div class="heading">
<h1>
  <a name="misc_Errors" id="misc_Errors"></a>
  <div class="permalink"><a href="#misc_Errors" class="permalink fas fa-link"></a></div>
  <p>Errors</p>

</h1>
</div>

<p>Applications running in Node.js will generally experience four categories of
errors:</p>
<ul>
<li>Standard JavaScript errors such as:<ul>
<li>{EvalError} : thrown when a call to <code>eval()</code> fails.</li>
<li>{SyntaxError} : thrown in response to improper JavaScript language
syntax.</li>
<li>{RangeError} : thrown when a value is not within an expected range</li>
<li>{ReferenceError} : thrown when using undefined variables</li>
<li>{TypeError} : thrown when passing arguments of the wrong type</li>
<li>{URIError} : thrown when a global URI handling function is misused.</li>
</ul>
</li>
<li>System errors triggered by underlying operating system constraints such
as attempting to open a file that does not exist, attempting to send data
over a closed socket, etc;</li>
<li>And User-specified errors triggered by application code.</li>
<li>Assertion Errors are a special class of error that can be triggered whenever
Node.js detects an exceptional logic violation that should never occur. These
are raised typically by the <code>assert</code> module.</li>
</ul>
<p>All JavaScript and System errors raised by Node.js inherit from, or are
instances of, the standard JavaScript {Error} class and are guaranteed
to provide <em>at least</em> the properties available on that class.</p>


<div class="heading">
<h2>
  <a name="misc_Error_Propagation_and_Interception" id="misc_Error_Propagation_and_Interception"></a>
  <div class="permalink"><a href="#misc_Error_Propagation_and_Interception" class="permalink fas fa-link"></a></div>
  <p>Error Propagation and Interception</p>

</h2>
</div>

<p>Node.js supports several mechanisms for propagating and handling errors that
occur while an application is running. How these errors are reported and
handled depends entirely on the type of Error and the style of the API that is
called.</p>
<p>All JavaScript errors are handled as exceptions that <em>immediately</em> generate
and throw an error using the standard JavaScript <code>throw</code> mechanism. These
are handled using the <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch"><code>try / catch</code> construct</a> provided by the
JavaScript language.</p>
<pre class="prettyprint"><code class="lang-js">// Throws with a ReferenceError because z is undefined
try {
  const m = 1;
  const n = m + z;
} catch (err) {
  // Handle the error here.
}
</code></pre>
<p>Any use of the JavaScript <code>throw</code> mechanism will raise an exception that
<em>must</em> be handled using <code>try / catch</code> or the Node.js process will exit
immediately.</p>
<p>With few exceptions, <em>Synchronous</em> APIs (any blocking method that does not
accept a <code>callback</code> function, such as <a href="fs.html#fs_fs_readfilesync_path_options"><code>fs.readFileSync</code></a>), will use <code>throw</code>
to report errors.</p>
<p>Errors that occur within <em>Asynchronous APIs</em> may be reported in multiple ways:</p>
<ul>
<li>Most asynchronous methods that accept a <code>callback</code> function will accept an
<code>Error</code> object passed as the first argument to that function. If that first
argument is not <code>null</code> and is an instance of <code>Error</code>, then an error occurred
that should be handled.</li>
</ul>
<!-- eslint-disable no-useless-return -->
<pre class="prettyprint"><code class="lang-js">  const fs = require(&#39;fs&#39;);
  fs.readFile(&#39;a file that does not exist&#39;, (err, data) =&gt; {
    if (err) {
      console.error(&#39;There was an error reading the file!&#39;, err);
      return;
    }
    // Otherwise handle the data
  });
</code></pre>
<ul>
<li><p>When an asynchronous method is called on an object that is an
<a href="events.html"><code>EventEmitter</code></a>, errors can be routed to that object&#39;s <code>&#39;error&#39;</code> event.</p>
<pre class="prettyprint"><code class="lang-js">const net = require(&#39;net&#39;);
const connection = net.connect(&#39;localhost&#39;);

// Adding an &#39;error&#39; event handler to a stream:
connection.on(&#39;error&#39;, (err) =&gt; {
  // If the connection is reset by the server, or if it can&#39;t
  // connect at all, or on any sort of error encountered by
  // the connection, the error will be sent here.
  console.error(err);
});

connection.pipe(process.stdout);
</code></pre>
</li>
<li><p>A handful of typically asynchronous methods in the Node.js API may still
use the <code>throw</code> mechanism to raise exceptions that must be handled using
<code>try / catch</code>. There is no comprehensive list of such methods; please
refer to the documentation of each method to determine the appropriate
error handling mechanism required.</p>
</li>
</ul>
<p>The use of the <code>&#39;error&#39;</code> event mechanism is most common for <a href="stream.html">stream-based</a>
and <a href="events.html#events_class_eventemitter">event emitter-based</a> APIs, which themselves represent a series of
asynchronous operations over time (as opposed to a single operation that may
pass or fail).</p>
<p>For <em>all</em> <a href="events.html"><code>EventEmitter</code></a> objects, if an <code>&#39;error&#39;</code> event handler is not
provided, the error will be thrown, causing the Node.js process to report an
unhandled exception and  crash unless either: The <a href="domain.html"><code>domain</code></a> module is
used appropriately or a handler has been registered for the
<a href="process.html#process_event_uncaughtexception"><code>process.on(&#39;uncaughtException&#39;)</code></a> event.</p>
<pre class="prettyprint"><code class="lang-js">const EventEmitter = require(&#39;events&#39;);
const ee = new EventEmitter();

setImmediate(() =&gt; {
  // This will crash the process because no &#39;error&#39; event
  // handler has been added.
  ee.emit(&#39;error&#39;, new Error(&#39;This will crash&#39;));
});
</code></pre>
<p>Errors generated in this way <em>cannot</em> be intercepted using <code>try / catch</code> as
they are thrown <em>after</em> the calling code has already exited.</p>
<p>Developers must refer to the documentation for each method to determine
exactly how errors raised by those methods are propagated.</p>


<div class="heading">
<h3>
  <a name="misc_Error_first_callbacks" id="misc_Error_first_callbacks"></a>
  <div class="permalink"><a href="#misc_Error_first_callbacks" class="permalink fas fa-link"></a></div>
  <p>Error-first callbacks</p>

</h3>
</div>

<p>Most asynchronous methods exposed by the Node.js core API follow an idiomatic
pattern  referred to as an <em>error-first callback</em> (sometimes referred to as
a <em>Node.js style callback</em>). With this pattern, a callback function is passed
to the method as an argument. When the operation either completes or an error
is raised, the callback function is called with
the Error object (if any) passed as the first argument. If no error was
raised, the first argument will be passed as <code>null</code>.</p>
<pre class="prettyprint"><code class="lang-js">const fs = require(&#39;fs&#39;);

function errorFirstCallback(err, data) {
  if (err) {
    console.error(&#39;There was an error&#39;, err);
    return;
  }
  console.log(data);
}

fs.readFile(&#39;/some/file/that/does-not-exist&#39;, errorFirstCallback);
fs.readFile(&#39;/some/file/that/does-exist&#39;, errorFirstCallback);
</code></pre>
<p>The JavaScript <code>try / catch</code> mechanism <strong>cannot</strong> be used to intercept errors
generated by asynchronous APIs.  A common mistake for beginners is to try to
use <code>throw</code> inside an error-first callback:</p>
<pre class="prettyprint"><code class="lang-js">// THIS WILL NOT WORK:
const fs = require(&#39;fs&#39;);

try {
  fs.readFile(&#39;/some/file/that/does-not-exist&#39;, (err, data) =&gt; {
    // mistaken assumption: throwing here...
    if (err) {
      throw err;
    }
  });
} catch (err) {
  // This will not catch the throw!
  console.error(err);
}
</code></pre>
<p>This will not work because the callback function passed to <code>fs.readFile()</code> is
called asynchronously. By the time the callback has been called, the
surrounding code (including the <code>try { } catch (err) { }</code> block will have
already exited. Throwing an error inside the callback <strong>can crash the Node.js
process</strong> in most cases. If <a href="domain.html">domains</a> are enabled, or a handler has been
registered with <code>process.on(&#39;uncaughtException&#39;)</code>, such errors can be
intercepted.</p>


<div class="heading">
<h2>
  <a name="misc_Exceptions_vs__Errors" id="misc_Exceptions_vs__Errors"></a>
  <div class="permalink"><a href="#misc_Exceptions_vs__Errors" class="permalink fas fa-link"></a></div>
  <p>Exceptions vs. Errors</p>

</h2>
</div>

<p>A JavaScript exception is a value that is thrown as a result of an invalid
operation or as the target of a <code>throw</code> statement. While it is not required
that these values are instances of <code>Error</code> or classes which inherit from
<code>Error</code>, all exceptions thrown by Node.js or the JavaScript runtime <em>will</em> be
instances of Error.</p>
<p>Some exceptions are <em>unrecoverable</em> at the JavaScript layer. Such exceptions
will <em>always</em> cause the Node.js process to crash. Examples include <code>assert()</code>
checks or <code>abort()</code> calls in the C++ layer.</p>


<div class="heading">
<h2>
  <a name="misc_system_errors" id="misc_system_errors"></a>
  <div class="permalink"><a href="#misc_system_errors" class="permalink fas fa-link"></a></div>
  <p>System Errors</p>

</h2>
</div>

<p>System errors are generated when exceptions occur within the program&#39;s
runtime environment. Typically, these are operational errors that occur
when an application violates an operating system constraint such as attempting
to read a file that does not exist or when the user does not have sufficient
permissions.</p>
<p>System errors are typically generated at the syscall level: an exhaustive list
of error codes and their meanings is available by running <code>man 2 intro</code> or
<code>man 3 errno</code> on most Unices; or <a href="http://man7.org/linux/man-pages/man3/errno.3.html">online</a>.</p>
<p>In Node.js, system errors are represented as augmented <code>Error</code> objects with
added properties.</p>


<div class="heading">
<h3>
  <a name="module_common_system_errors" id="module_common_system_errors"></a>
  <div class="permalink"><a href="#module_common_system_errors" class="permalink fas fa-link"></a></div>
  <p>Common System Errors</p>

</h3>
</div>

<p>This list is <strong>not exhaustive</strong>, but enumerates many of the common system
errors encountered when writing a Node.js program. An exhaustive list may be
found <a href="http://man7.org/linux/man-pages/man3/errno.3.html">here</a>.</p>
<ul>
<li><p><code>EACCES</code> (Permission denied): An attempt was made to access a file in a way
forbidden by its file access permissions.</p>
</li>
<li><p><code>EADDRINUSE</code> (Address already in use):  An attempt to bind a server
(<a href="net.html"><code>net</code></a>, <a href="http.html"><code>http</code></a>, or <a href="https.html"><code>https</code></a>) to a local address failed due to
another server on the local system already occupying that address.</p>
</li>
<li><p><code>ECONNREFUSED</code> (Connection refused): No connection could be made because the
target machine actively refused it. This usually results from trying to
connect to a service that is inactive on the foreign host.</p>
</li>
<li><p><code>ECONNRESET</code> (Connection reset by peer): A connection was forcibly closed by
a peer. This normally results from a loss of the connection on the remote
socket due to a timeout or reboot. Commonly encountered via the <a href="http.html"><code>http</code></a>
and <a href="net.html"><code>net</code></a> modules.</p>
</li>
<li><p><code>EEXIST</code> (File exists): An existing file was the target of an operation that
required that the target not exist.</p>
</li>
<li><p><code>EISDIR</code> (Is a directory): An operation expected a file, but the given
pathname was a directory.</p>
</li>
<li><p><code>EMFILE</code> (Too many open files in system): Maximum number of
<a href="https://en.wikipedia.org/wiki/File_descriptor">file descriptors</a> allowable on the system has been reached, and
requests for another descriptor cannot be fulfilled until at least one
has been closed. This is encountered when opening many files at once in
parallel, especially on systems (in particular, macOS) where there is a low
file descriptor limit for processes. To remedy a low limit, run
<code>ulimit -n 2048</code> in the same shell that will run the Node.js process.</p>
</li>
<li><p><code>ENOENT</code> (No such file or directory): Commonly raised by <a href="fs.html"><code>fs</code></a> operations
to indicate that a component of the specified pathname does not exist -- no
entity (file or directory) could be found by the given path.</p>
</li>
<li><p><code>ENOTDIR</code> (Not a directory): A component of the given pathname existed, but
was not a directory as expected. Commonly raised by <a href="fs.html#fs_fs_readdir_path_options_callback"><code>fs.readdir</code></a>.</p>
</li>
<li><p><code>ENOTEMPTY</code> (Directory not empty): A directory with entries was the target
of an operation that requires an empty directory -- usually <a href="fs.html#fs_fs_unlink_path_callback"><code>fs.unlink</code></a>.</p>
</li>
<li><p><code>EPERM</code> (Operation not permitted): An attempt was made to perform an
operation that requires elevated privileges.</p>
</li>
<li><p><code>EPIPE</code> (Broken pipe): A write on a pipe, socket, or FIFO for which there is
no process to read the data. Commonly encountered at the <a href="net.html"><code>net</code></a> and
<a href="http.html"><code>http</code></a> layers, indicative that the remote side of the stream being
written to has been closed.</p>
</li>
<li><p><code>ETIMEDOUT</code> (Operation timed out): A connect or send request failed because
the connected party did not properly respond after a period of time. Usually
encountered by <a href="http.html"><code>http</code></a> or <a href="net.html"><code>net</code></a> -- often a sign that a <code>socket.end()</code>
was not properly called.</p>
</li>
</ul>
<p><a id="nodejs-error-codes"></a></p>

<div class='expandable-header' id='class_System-expand'>
<div class="heading">
    <h3>
        <a name="class_System" id="class_System"></a>
        <i class='expandable-icon fas fa-caret-right' id="class_System-expand-icon"></i>
        <div class="permalink"><a href="#class_System" class="permalink fas fa-link"></a></div>
        <p>Class: System Error</p>

    </h3>
</div>

</div>
<div class='expandable-content' id='class_System-expand-content'>


<div class="heading">
<h4>
  <a name="subgroup_class_System_Properties" id="subgroup_class_System_Properties"></a>
  <div class="permalink"><a href="#subgroup_class_System_Properties" class="permalink fas fa-link"></a></div>
  <p>Properties</p>

</h4>
</div>


<div class='expandable-header' id='property_code-expand'>
<div class="heading">
    <h5>
        <a name="property_code" id="property_code"></a>
        <i class='expandable-icon fas fa-caret-right' id="property_code-expand-icon"></i>
        <div class="permalink"><a href="#property_code" class="permalink fas fa-link"></a></div>
        <p><code>code</code> {string} </p>

    </h5>
</div>

</div>
<div class='expandable-content' id='property_code-expand-content'>
<p>The <code>error.code</code> property is a string representing the error code, which is
typically <code>E</code> followed by a sequence of capital letters.</p>


</div><div class='expandable-header' id='property_errno-expand'>
<div class="heading">
    <h5>
        <a name="property_errno" id="property_errno"></a>
        <i class='expandable-icon fas fa-caret-right' id="property_errno-expand-icon"></i>
        <div class="permalink"><a href="#property_errno" class="permalink fas fa-link"></a></div>
        <p><code>errno</code> {string|number} </p>

    </h5>
</div>

</div>
<div class='expandable-content' id='property_errno-expand-content'>
<p>The <code>error.errno</code> property is a number or a string.
The number is a <strong>negative</strong> value which corresponds to the error code defined
in <a href="http://docs.libuv.org/en/v1.x/errors.html"><code>libuv Error handling</code></a>. See uv-errno.h header file
(<code>deps/uv/include/uv-errno.h</code> in the Node.js source tree) for details. In case
of a string, it is the same as <code>error.code</code>.</p>


</div><div class='expandable-header' id='property_syscall-expand'>
<div class="heading">
    <h5>
        <a name="property_syscall" id="property_syscall"></a>
        <i class='expandable-icon fas fa-caret-right' id="property_syscall-expand-icon"></i>
        <div class="permalink"><a href="#property_syscall" class="permalink fas fa-link"></a></div>
        <p><code>syscall</code> {string} </p>

    </h5>
</div>

</div>
<div class='expandable-content' id='property_syscall-expand-content'>
<p>The <code>error.syscall</code> property is a string describing the <a href="http://man7.org/linux/man-pages/man2/syscall.2.html">syscall</a> that failed.</p>


</div><div class='expandable-header' id='property_path-expand'>
<div class="heading">
    <h5>
        <a name="property_path" id="property_path"></a>
        <i class='expandable-icon fas fa-caret-right' id="property_path-expand-icon"></i>
        <div class="permalink"><a href="#property_path" class="permalink fas fa-link"></a></div>
        <p><code>path</code> {string} </p>

    </h5>
</div>

</div>
<div class='expandable-content' id='property_path-expand-content'>
<p>When present (e.g. in <code>fs</code> or <code>child_process</code>), the <code>error.path</code> property is a
string containing a relevant invalid pathname.</p>


</div><div class='expandable-header' id='property_address-expand'>
<div class="heading">
    <h5>
        <a name="property_address" id="property_address"></a>
        <i class='expandable-icon fas fa-caret-right' id="property_address-expand-icon"></i>
        <div class="permalink"><a href="#property_address" class="permalink fas fa-link"></a></div>
        <p><code>address</code> {string} </p>

    </h5>
</div>

</div>
<div class='expandable-content' id='property_address-expand-content'>
<p>When present (e.g. in <code>net</code> or <code>dgram</code>), the <code>error.address</code> property is a
string describing the address to which the connection failed.</p>


</div><div class='expandable-header' id='property_port-expand'>
<div class="heading">
    <h5>
        <a name="property_port" id="property_port"></a>
        <i class='expandable-icon fas fa-caret-right' id="property_port-expand-icon"></i>
        <div class="permalink"><a href="#property_port" class="permalink fas fa-link"></a></div>
        <p><code>port</code> {number} </p>

    </h5>
</div>

</div>
<div class='expandable-content' id='property_port-expand-content'>
<p>When present (e.g. in <code>net</code> or <code>dgram</code>), the <code>error.port</code> property is a number
representing the connection&#39;s port that is not available.</p>


</div>
</div>
<div class="heading">
<h2>
  <a name="misc_node_js_error_codes" id="misc_node_js_error_codes"></a>
  <div class="permalink"><a href="#misc_node_js_error_codes" class="permalink fas fa-link"></a></div>
  <p>Node.js Error Codes</p>

</h2>
</div>

<p><a id="ERR_ARG_NOT_ITERABLE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_arg_not_iterable" id="module_err_arg_not_iterable"></a>
  <div class="permalink"><a href="#module_err_arg_not_iterable" class="permalink fas fa-link"></a></div>
  <p>ERR_ARG_NOT_ITERABLE</p>

</h3>
</div>

<p>An iterable argument (i.e. a value that works with <code>for...of</code> loops) was
required, but not provided to a Node.js API.</p>
<p><a id="ERR_ASSERTION"></a></p>


<div class="heading">
<h3>
  <a name="module_err_assertion" id="module_err_assertion"></a>
  <div class="permalink"><a href="#module_err_assertion" class="permalink fas fa-link"></a></div>
  <p>ERR_ASSERTION</p>

</h3>
</div>

<p>A special type of error that can be triggered whenever Node.js detects an
exceptional logic violation that should never occur. These are raised typically
by the <code>assert</code> module.</p>
<p><a id="ERR_ASYNC_CALLBACK"></a></p>


<div class="heading">
<h3>
  <a name="module_err_async_callback" id="module_err_async_callback"></a>
  <div class="permalink"><a href="#module_err_async_callback" class="permalink fas fa-link"></a></div>
  <p>ERR_ASYNC_CALLBACK</p>

</h3>
</div>

<p>An attempt was made to register something that is not a function as an
<code>AsyncHooks</code> callback.</p>
<p><a id="ERR_ASYNC_TYPE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_async_type" id="module_err_async_type"></a>
  <div class="permalink"><a href="#module_err_async_type" class="permalink fas fa-link"></a></div>
  <p>ERR_ASYNC_TYPE</p>

</h3>
</div>

<p>The type of an asynchronous resource was invalid. Note that users are also able
to define their own types if using the public embedder API.</p>
<p><a id="ERR_BUFFER_OUT_OF_BOUNDS"></a></p>


<div class="heading">
<h3>
  <a name="module_err_buffer_out_of_bounds" id="module_err_buffer_out_of_bounds"></a>
  <div class="permalink"><a href="#module_err_buffer_out_of_bounds" class="permalink fas fa-link"></a></div>
  <p>ERR_BUFFER_OUT_OF_BOUNDS</p>

</h3>
</div>

<p>An operation outside the bounds of a <code>Buffer</code> was attempted.</p>
<p><a id="ERR_BUFFER_TOO_LARGE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_buffer_too_large" id="module_err_buffer_too_large"></a>
  <div class="permalink"><a href="#module_err_buffer_too_large" class="permalink fas fa-link"></a></div>
  <p>ERR_BUFFER_TOO_LARGE</p>

</h3>
</div>

<p>An attempt has been made to create a <code>Buffer</code> larger than the maximum allowed
size.</p>
<p><a id="ERR_CHILD_CLOSED_BEFORE_REPLY"></a></p>


<div class="heading">
<h3>
  <a name="module_err_child_closed_before_reply" id="module_err_child_closed_before_reply"></a>
  <div class="permalink"><a href="#module_err_child_closed_before_reply" class="permalink fas fa-link"></a></div>
  <p>ERR_CHILD_CLOSED_BEFORE_REPLY</p>

</h3>
</div>

<p>A child process was closed before the parent received a reply.</p>
<p><a id="ERR_CONSOLE_WRITABLE_STREAM"></a></p>


<div class="heading">
<h3>
  <a name="module_err_console_writable_stream" id="module_err_console_writable_stream"></a>
  <div class="permalink"><a href="#module_err_console_writable_stream" class="permalink fas fa-link"></a></div>
  <p>ERR_CONSOLE_WRITABLE_STREAM</p>

</h3>
</div>

<p><code>Console</code> was instantiated without <code>stdout</code> stream, or <code>Console</code> has a
non-writable <code>stdout</code> or <code>stderr</code> stream.</p>
<p><a id="ERR_CPU_USAGE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_cpu_usage" id="module_err_cpu_usage"></a>
  <div class="permalink"><a href="#module_err_cpu_usage" class="permalink fas fa-link"></a></div>
  <p>ERR_CPU_USAGE</p>

</h3>
</div>

<p>The native call from <code>process.cpuUsage</code> could not be processed.</p>
<p><a id="ERR_CRYPTO_CUSTOM_ENGINE_NOT_SUPPORTED"></a></p>


<div class="heading">
<h3>
  <a name="module_err_crypto_custom_engine_not_supported" id="module_err_crypto_custom_engine_not_supported"></a>
  <div class="permalink"><a href="#module_err_crypto_custom_engine_not_supported" class="permalink fas fa-link"></a></div>
  <p>ERR_CRYPTO_CUSTOM_ENGINE_NOT_SUPPORTED</p>

</h3>
</div>

<p>A client certificate engine was requested that is not supported by the version
of OpenSSL being used.</p>
<p><a id="ERR_CRYPTO_ECDH_INVALID_FORMAT"></a></p>


<div class="heading">
<h3>
  <a name="module_err_crypto_ecdh_invalid_format" id="module_err_crypto_ecdh_invalid_format"></a>
  <div class="permalink"><a href="#module_err_crypto_ecdh_invalid_format" class="permalink fas fa-link"></a></div>
  <p>ERR_CRYPTO_ECDH_INVALID_FORMAT</p>

</h3>
</div>

<p>An invalid value for the <code>format</code> argument was passed to the <code>crypto.ECDH()</code>
class <code>getPublicKey()</code> method.</p>
<p><a id="ERR_CRYPTO_ENGINE_UNKNOWN"></a></p>


<div class="heading">
<h3>
  <a name="module_err_crypto_engine_unknown" id="module_err_crypto_engine_unknown"></a>
  <div class="permalink"><a href="#module_err_crypto_engine_unknown" class="permalink fas fa-link"></a></div>
  <p>ERR_CRYPTO_ENGINE_UNKNOWN</p>

</h3>
</div>

<p>An invalid crypto engine identifier was passed to
<a href="crypto.html#crypto_crypto_setengine_engine_flags"><code>require(&#39;crypto&#39;).setEngine()</code></a>.</p>
<p><a id="ERR_CRYPTO_FIPS_FORCED"></a></p>


<div class="heading">
<h3>
  <a name="module_err_crypto_fips_forced" id="module_err_crypto_fips_forced"></a>
  <div class="permalink"><a href="#module_err_crypto_fips_forced" class="permalink fas fa-link"></a></div>
  <p>ERR_CRYPTO_FIPS_FORCED</p>

</h3>
</div>

<p>The <a href="cli.html#cli_force_fips"><code>--force-fips</code></a> command-line argument was used but there was an attempt
to enable or disable FIPS mode in the <code>crypto</code> module.</p>
<p><a id="ERR_CRYPTO_FIPS_UNAVAILABLE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_crypto_fips_unavailable" id="module_err_crypto_fips_unavailable"></a>
  <div class="permalink"><a href="#module_err_crypto_fips_unavailable" class="permalink fas fa-link"></a></div>
  <p>ERR_CRYPTO_FIPS_UNAVAILABLE</p>

</h3>
</div>

<p>An attempt was made to enable or disable FIPS mode, but FIPS mode was not
available.</p>
<p><a id="ERR_CRYPTO_HASH_DIGEST_NO_UTF16"></a></p>


<div class="heading">
<h3>
  <a name="module_err_crypto_hash_digest_no_utf16" id="module_err_crypto_hash_digest_no_utf16"></a>
  <div class="permalink"><a href="#module_err_crypto_hash_digest_no_utf16" class="permalink fas fa-link"></a></div>
  <p>ERR_CRYPTO_HASH_DIGEST_NO_UTF16</p>

</h3>
</div>

<p>The UTF-16 encoding was used with <a href="crypto.html#crypto_hash_digest_encoding"><code>hash.digest()</code></a>. While the
<code>hash.digest()</code> method does allow an <code>encoding</code> argument to be passed in,
causing the method to return a string rather than a <code>Buffer</code>, the UTF-16
encoding (e.g. <code>ucs</code> or <code>utf16le</code>) is not supported.</p>
<p><a id="ERR_CRYPTO_HASH_FINALIZED"></a></p>


<div class="heading">
<h3>
  <a name="module_err_crypto_hash_finalized" id="module_err_crypto_hash_finalized"></a>
  <div class="permalink"><a href="#module_err_crypto_hash_finalized" class="permalink fas fa-link"></a></div>
  <p>ERR_CRYPTO_HASH_FINALIZED</p>

</h3>
</div>

<p><a href="crypto.html#crypto_hash_digest_encoding"><code>hash.digest()</code></a> was called multiple times. The <code>hash.digest()</code> method must
be called no more than one time per instance of a <code>Hash</code> object.</p>
<p><a id="ERR_CRYPTO_HASH_UPDATE_FAILED"></a></p>


<div class="heading">
<h3>
  <a name="module_err_crypto_hash_update_failed" id="module_err_crypto_hash_update_failed"></a>
  <div class="permalink"><a href="#module_err_crypto_hash_update_failed" class="permalink fas fa-link"></a></div>
  <p>ERR_CRYPTO_HASH_UPDATE_FAILED</p>

</h3>
</div>

<p><a href="crypto.html#crypto_hash_update_data_inputencoding"><code>hash.update()</code></a> failed for any reason. This should rarely, if ever, happen.</p>
<p><a id="ERR_CRYPTO_INVALID_DIGEST"></a></p>


<div class="heading">
<h3>
  <a name="module_err_crypto_invalid_digest" id="module_err_crypto_invalid_digest"></a>
  <div class="permalink"><a href="#module_err_crypto_invalid_digest" class="permalink fas fa-link"></a></div>
  <p>ERR_CRYPTO_INVALID_DIGEST</p>

</h3>
</div>

<p>An invalid <a href="crypto.html#crypto_crypto_gethashes">crypto digest algorithm</a> was specified.</p>
<p><a id="ERR_CRYPTO_SIGN_KEY_REQUIRED"></a></p>


<div class="heading">
<h3>
  <a name="module_err_crypto_sign_key_required" id="module_err_crypto_sign_key_required"></a>
  <div class="permalink"><a href="#module_err_crypto_sign_key_required" class="permalink fas fa-link"></a></div>
  <p>ERR_CRYPTO_SIGN_KEY_REQUIRED</p>

</h3>
</div>

<p>A signing <code>key</code> was not provided to the <a href="crypto.html#crypto_sign_sign_privatekey_outputformat"><code>sign.sign()</code></a> method.</p>
<p><a id="ERR_CRYPTO_TIMING_SAFE_EQUAL_LENGTH"></a></p>


<div class="heading">
<h3>
  <a name="module_err_crypto_timing_safe_equal_length" id="module_err_crypto_timing_safe_equal_length"></a>
  <div class="permalink"><a href="#module_err_crypto_timing_safe_equal_length" class="permalink fas fa-link"></a></div>
  <p>ERR_CRYPTO_TIMING_SAFE_EQUAL_LENGTH</p>

</h3>
</div>

<p><a href="crypto.html#crypto_crypto_timingsafeequal_a_b"><code>crypto.timingSafeEqual()</code></a> was called with <code>Buffer</code>, <code>TypedArray</code>, or
<code>DataView</code> arguments of different lengths.</p>
<p><a id="ERR_DNS_SET_SERVERS_FAILED"></a></p>


<div class="heading">
<h3>
  <a name="module_err_dns_set_servers_failed" id="module_err_dns_set_servers_failed"></a>
  <div class="permalink"><a href="#module_err_dns_set_servers_failed" class="permalink fas fa-link"></a></div>
  <p>ERR_DNS_SET_SERVERS_FAILED</p>

</h3>
</div>

<p><code>c-ares</code> failed to set the DNS server.</p>
<p><a id="ERR_DOMAIN_CALLBACK_NOT_AVAILABLE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_domain_callback_not_available" id="module_err_domain_callback_not_available"></a>
  <div class="permalink"><a href="#module_err_domain_callback_not_available" class="permalink fas fa-link"></a></div>
  <p>ERR_DOMAIN_CALLBACK_NOT_AVAILABLE</p>

</h3>
</div>

<p>The <code>domain</code> module was not usable since it could not establish the required
error handling hooks, because
<a href="process.html#process_process_setuncaughtexceptioncapturecallback_fn"><code>process.setUncaughtExceptionCaptureCallback()</code></a> had been called at an
earlier point in time.</p>
<p><a id="ERR_DOMAIN_CANNOT_SET_UNCAUGHT_EXCEPTION_CAPTURE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_domain_cannot_set_uncaught_exception_capture" id="module_err_domain_cannot_set_uncaught_exception_capture"></a>
  <div class="permalink"><a href="#module_err_domain_cannot_set_uncaught_exception_capture" class="permalink fas fa-link"></a></div>
  <p>ERR_DOMAIN_CANNOT_SET_UNCAUGHT_EXCEPTION_CAPTURE</p>

</h3>
</div>

<p><a href="process.html#process_process_setuncaughtexceptioncapturecallback_fn"><code>process.setUncaughtExceptionCaptureCallback()</code></a> could not be called
because the <code>domain</code> module has been loaded at an earlier point in time.</p>
<p>The stack trace is extended to include the point in time at which the
<code>domain</code> module had been loaded.</p>
<p><a id="ERR_ENCODING_INVALID_ENCODED_DATA"></a></p>


<div class="heading">
<h3>
  <a name="module_err_encoding_invalid_encoded_data" id="module_err_encoding_invalid_encoded_data"></a>
  <div class="permalink"><a href="#module_err_encoding_invalid_encoded_data" class="permalink fas fa-link"></a></div>
  <p>ERR_ENCODING_INVALID_ENCODED_DATA</p>

</h3>
</div>

<p>Data provided to <code>util.TextDecoder()</code> API was invalid according to the encoding
provided.</p>
<p><a id="ERR_ENCODING_NOT_SUPPORTED"></a></p>


<div class="heading">
<h3>
  <a name="module_err_encoding_not_supported" id="module_err_encoding_not_supported"></a>
  <div class="permalink"><a href="#module_err_encoding_not_supported" class="permalink fas fa-link"></a></div>
  <p>ERR_ENCODING_NOT_SUPPORTED</p>

</h3>
</div>

<p>Encoding provided to <code>util.TextDecoder()</code> API was not one of the
<a href="util.html#util_whatwg_supported_encodings">WHATWG Supported Encodings</a>.</p>
<p><a id="ERR_FALSY_VALUE_REJECTION"></a></p>


<div class="heading">
<h3>
  <a name="module_err_falsy_value_rejection" id="module_err_falsy_value_rejection"></a>
  <div class="permalink"><a href="#module_err_falsy_value_rejection" class="permalink fas fa-link"></a></div>
  <p>ERR_FALSY_VALUE_REJECTION</p>

</h3>
</div>

<p>A <code>Promise</code> that was callbackified via <code>util.callbackify()</code> was rejected with a
falsy value.</p>
<p><a id="ERR_HTTP_HEADERS_SENT"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http_headers_sent" id="module_err_http_headers_sent"></a>
  <div class="permalink"><a href="#module_err_http_headers_sent" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP_HEADERS_SENT</p>

</h3>
</div>

<p>An attempt was made to add more headers after the headers had already been sent.</p>
<p><a id="ERR_HTTP_INVALID_CHAR"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http_invalid_char" id="module_err_http_invalid_char"></a>
  <div class="permalink"><a href="#module_err_http_invalid_char" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP_INVALID_CHAR</p>

</h3>
</div>

<p>An invalid character was found in an HTTP response status message (reason
phrase).</p>
<p><a id="ERR_HTTP_INVALID_STATUS_CODE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http_invalid_status_code" id="module_err_http_invalid_status_code"></a>
  <div class="permalink"><a href="#module_err_http_invalid_status_code" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP_INVALID_STATUS_CODE</p>

</h3>
</div>

<p>Status code was outside the regular status code range (100-999).</p>
<p><a id="ERR_HTTP_TRAILER_INVALID"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http_trailer_invalid" id="module_err_http_trailer_invalid"></a>
  <div class="permalink"><a href="#module_err_http_trailer_invalid" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP_TRAILER_INVALID</p>

</h3>
</div>

<p>The <code>Trailer</code> header was set even though the transfer encoding does not support
that.</p>
<p><a id="ERR_HTTP2_ALREADY_SHUTDOWN"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_already_shutdown" id="module_err_http2_already_shutdown"></a>
  <div class="permalink"><a href="#module_err_http2_already_shutdown" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_ALREADY_SHUTDOWN</p>

</h3>
</div>

<p>Occurs with multiple attempts to shutdown an HTTP/2 session.</p>
<p><a id="ERR_HTTP2_ALTSVC_INVALID_ORIGIN"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_altsvc_invalid_origin" id="module_err_http2_altsvc_invalid_origin"></a>
  <div class="permalink"><a href="#module_err_http2_altsvc_invalid_origin" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_ALTSVC_INVALID_ORIGIN</p>

</h3>
</div>

<p>HTTP/2 ALTSVC frames require a valid origin.</p>
<p><a id="ERR_HTTP2_ALTSVC_LENGTH"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_altsvc_length" id="module_err_http2_altsvc_length"></a>
  <div class="permalink"><a href="#module_err_http2_altsvc_length" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_ALTSVC_LENGTH</p>

</h3>
</div>

<p>HTTP/2 ALTSVC frames are limited to a maximum of 16,382 payload bytes.</p>
<p><a id="ERR_HTTP2_CONNECT_AUTHORITY"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_connect_authority" id="module_err_http2_connect_authority"></a>
  <div class="permalink"><a href="#module_err_http2_connect_authority" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_CONNECT_AUTHORITY</p>

</h3>
</div>

<p>For HTTP/2 requests using the <code>CONNECT</code> method, the <code>:authority</code> pseudo-header
is required.</p>
<p><a id="ERR_HTTP2_CONNECT_PATH"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_connect_path" id="module_err_http2_connect_path"></a>
  <div class="permalink"><a href="#module_err_http2_connect_path" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_CONNECT_PATH</p>

</h3>
</div>

<p>For HTTP/2 requests using the <code>CONNECT</code> method, the <code>:path</code> pseudo-header is
forbidden.</p>
<p><a id="ERR_HTTP2_CONNECT_SCHEME"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_connect_scheme" id="module_err_http2_connect_scheme"></a>
  <div class="permalink"><a href="#module_err_http2_connect_scheme" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_CONNECT_SCHEME</p>

</h3>
</div>

<p>For HTTP/2 requests using the <code>CONNECT</code> method, the <code>:scheme</code> pseudo-header is
forbidden.</p>
<p><a id="ERR_HTTP2_FRAME_ERROR"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_frame_error" id="module_err_http2_frame_error"></a>
  <div class="permalink"><a href="#module_err_http2_frame_error" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_FRAME_ERROR</p>

</h3>
</div>

<p>A failure occurred sending an individual frame on the HTTP/2 session.</p>
<p><a id="ERR_HTTP2_GOAWAY_SESSION"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_goaway_session" id="module_err_http2_goaway_session"></a>
  <div class="permalink"><a href="#module_err_http2_goaway_session" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_GOAWAY_SESSION</p>

</h3>
</div>

<p>New HTTP/2 Streams may not be opened after the <code>Http2Session</code> has received a
<code>GOAWAY</code> frame from the connected peer.</p>
<p><a id="ERR_HTTP2_HEADER_REQUIRED"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_header_required" id="module_err_http2_header_required"></a>
  <div class="permalink"><a href="#module_err_http2_header_required" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_HEADER_REQUIRED</p>

</h3>
</div>

<p>A required header was missing in an HTTP/2 message.</p>
<p><a id="ERR_HTTP2_HEADER_SINGLE_VALUE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_header_single_value" id="module_err_http2_header_single_value"></a>
  <div class="permalink"><a href="#module_err_http2_header_single_value" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_HEADER_SINGLE_VALUE</p>

</h3>
</div>

<p>Multiple values were provided for an HTTP/2 header field that was required to
have only a single value.</p>
<p><a id="ERR_HTTP2_HEADERS_AFTER_RESPOND"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_headers_after_respond" id="module_err_http2_headers_after_respond"></a>
  <div class="permalink"><a href="#module_err_http2_headers_after_respond" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_HEADERS_AFTER_RESPOND</p>

</h3>
</div>

<p>An additional headers was specified after an HTTP/2 response was initiated.</p>
<p><a id="ERR_HTTP2_HEADERS_OBJECT"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_headers_object" id="module_err_http2_headers_object"></a>
  <div class="permalink"><a href="#module_err_http2_headers_object" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_HEADERS_OBJECT</p>

</h3>
</div>

<p>An HTTP/2 Headers Object was expected.</p>
<p><a id="ERR_HTTP2_HEADERS_SENT"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_headers_sent" id="module_err_http2_headers_sent"></a>
  <div class="permalink"><a href="#module_err_http2_headers_sent" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_HEADERS_SENT</p>

</h3>
</div>

<p>An attempt was made to send multiple response headers.</p>
<p><a id="ERR_HTTP2_INFO_HEADERS_AFTER_RESPOND"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_info_headers_after_respond" id="module_err_http2_info_headers_after_respond"></a>
  <div class="permalink"><a href="#module_err_http2_info_headers_after_respond" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_INFO_HEADERS_AFTER_RESPOND</p>

</h3>
</div>

<p>HTTP/2 Informational headers must only be sent <em>prior</em> to calling the
<code>Http2Stream.prototype.respond()</code> method.</p>
<p><a id="ERR_HTTP2_INFO_STATUS_NOT_ALLOWED"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_info_status_not_allowed" id="module_err_http2_info_status_not_allowed"></a>
  <div class="permalink"><a href="#module_err_http2_info_status_not_allowed" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_INFO_STATUS_NOT_ALLOWED</p>

</h3>
</div>

<p>Informational HTTP status codes (<code>1xx</code>) may not be set as the response status
code on HTTP/2 responses.</p>
<p><a id="ERR_HTTP2_INVALID_CONNECTION_HEADERS"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_invalid_connection_headers" id="module_err_http2_invalid_connection_headers"></a>
  <div class="permalink"><a href="#module_err_http2_invalid_connection_headers" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_INVALID_CONNECTION_HEADERS</p>

</h3>
</div>

<p>HTTP/1 connection specific headers are forbidden to be used in HTTP/2
requests and responses.</p>
<p><a id="ERR_HTTP2_INVALID_HEADER_VALUE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_invalid_header_value" id="module_err_http2_invalid_header_value"></a>
  <div class="permalink"><a href="#module_err_http2_invalid_header_value" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_INVALID_HEADER_VALUE</p>

</h3>
</div>

<p>An invalid HTTP/2 header value was specified.</p>
<p><a id="ERR_HTTP2_INVALID_INFO_STATUS"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_invalid_info_status" id="module_err_http2_invalid_info_status"></a>
  <div class="permalink"><a href="#module_err_http2_invalid_info_status" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_INVALID_INFO_STATUS</p>

</h3>
</div>

<p>An invalid HTTP informational status code has been specified. Informational
status codes must be an integer between <code>100</code> and <code>199</code> (inclusive).</p>
<p><a id="ERR_HTTP2_INVALID_PACKED_SETTINGS_LENGTH"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_invalid_packed_settings_length" id="module_err_http2_invalid_packed_settings_length"></a>
  <div class="permalink"><a href="#module_err_http2_invalid_packed_settings_length" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_INVALID_PACKED_SETTINGS_LENGTH</p>

</h3>
</div>

<p>Input <code>Buffer</code> and <code>Uint8Array</code> instances passed to the
<code>http2.getUnpackedSettings()</code> API must have a length that is a multiple of
six.</p>
<p><a id="ERR_HTTP2_INVALID_PSEUDOHEADER"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_invalid_pseudoheader" id="module_err_http2_invalid_pseudoheader"></a>
  <div class="permalink"><a href="#module_err_http2_invalid_pseudoheader" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_INVALID_PSEUDOHEADER</p>

</h3>
</div>

<p>Only valid HTTP/2 pseudoheaders (<code>:status</code>, <code>:path</code>, <code>:authority</code>, <code>:scheme</code>,
and <code>:method</code>) may be used.</p>
<p><a id="ERR_HTTP2_INVALID_SESSION"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_invalid_session" id="module_err_http2_invalid_session"></a>
  <div class="permalink"><a href="#module_err_http2_invalid_session" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_INVALID_SESSION</p>

</h3>
</div>

<p>An action was performed on an <code>Http2Session</code> object that had already been
destroyed.</p>
<p><a id="ERR_HTTP2_INVALID_SETTING_VALUE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_invalid_setting_value" id="module_err_http2_invalid_setting_value"></a>
  <div class="permalink"><a href="#module_err_http2_invalid_setting_value" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_INVALID_SETTING_VALUE</p>

</h3>
</div>

<p>An invalid value has been specified for an HTTP/2 setting.</p>
<p><a id="ERR_HTTP2_INVALID_STREAM"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_invalid_stream" id="module_err_http2_invalid_stream"></a>
  <div class="permalink"><a href="#module_err_http2_invalid_stream" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_INVALID_STREAM</p>

</h3>
</div>

<p>An operation was performed on a stream that had already been destroyed.</p>
<p><a id="ERR_HTTP2_MAX_PENDING_SETTINGS_ACK"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_max_pending_settings_ack" id="module_err_http2_max_pending_settings_ack"></a>
  <div class="permalink"><a href="#module_err_http2_max_pending_settings_ack" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_MAX_PENDING_SETTINGS_ACK</p>

</h3>
</div>

<p>Whenever an HTTP/2 <code>SETTINGS</code> frame is sent to a connected peer, the peer is
required to send an acknowledgment that it has received and applied the new
<code>SETTINGS</code>. By default, a maximum number of unacknowledged <code>SETTINGS</code> frames may
be sent at any given time. This error code is used when that limit has been
reached.</p>
<p><a id="ERR_HTTP2_NO_SOCKET_MANIPULATION"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_no_socket_manipulation" id="module_err_http2_no_socket_manipulation"></a>
  <div class="permalink"><a href="#module_err_http2_no_socket_manipulation" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_NO_SOCKET_MANIPULATION</p>

</h3>
</div>

<p>An attempt was made to directly manipulate (read, write, pause, resume, etc.) a
socket attached to an <code>Http2Session</code>.</p>
<p><a id="ERR_HTTP2_OUT_OF_STREAMS"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_out_of_streams" id="module_err_http2_out_of_streams"></a>
  <div class="permalink"><a href="#module_err_http2_out_of_streams" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_OUT_OF_STREAMS</p>

</h3>
</div>

<p>The number of streams created on a single HTTP/2 session reached the maximum
limit.</p>
<p><a id="ERR_HTTP2_PAYLOAD_FORBIDDEN"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_payload_forbidden" id="module_err_http2_payload_forbidden"></a>
  <div class="permalink"><a href="#module_err_http2_payload_forbidden" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_PAYLOAD_FORBIDDEN</p>

</h3>
</div>

<p>A message payload was specified for an HTTP response code for which a payload is
forbidden.</p>
<p><a id="ERR_HTTP2_PING_CANCEL"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_ping_cancel" id="module_err_http2_ping_cancel"></a>
  <div class="permalink"><a href="#module_err_http2_ping_cancel" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_PING_CANCEL</p>

</h3>
</div>

<p>An HTTP/2 ping was canceled.</p>
<p><a id="ERR_HTTP2_PING_LENGTH"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_ping_length" id="module_err_http2_ping_length"></a>
  <div class="permalink"><a href="#module_err_http2_ping_length" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_PING_LENGTH</p>

</h3>
</div>

<p>HTTP/2 ping payloads must be exactly 8 bytes in length.</p>
<p><a id="ERR_HTTP2_PSEUDOHEADER_NOT_ALLOWED"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_pseudoheader_not_allowed" id="module_err_http2_pseudoheader_not_allowed"></a>
  <div class="permalink"><a href="#module_err_http2_pseudoheader_not_allowed" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_PSEUDOHEADER_NOT_ALLOWED</p>

</h3>
</div>

<p>An HTTP/2 pseudo-header has been used inappropriately. Pseudo-headers are header
key names that begin with the <code>:</code> prefix.</p>
<p><a id="ERR_HTTP2_PUSH_DISABLED"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_push_disabled" id="module_err_http2_push_disabled"></a>
  <div class="permalink"><a href="#module_err_http2_push_disabled" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_PUSH_DISABLED</p>

</h3>
</div>

<p>An attempt was made to create a push stream, which had been disabled by the
client.</p>
<p><a id="ERR_HTTP2_SEND_FILE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_send_file" id="module_err_http2_send_file"></a>
  <div class="permalink"><a href="#module_err_http2_send_file" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_SEND_FILE</p>

</h3>
</div>

<p>An attempt was made to use the <code>Http2Stream.prototype.responseWithFile()</code> API to
send something other than a regular file.</p>
<p><a id="ERR_HTTP2_SESSION_ERROR"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_session_error" id="module_err_http2_session_error"></a>
  <div class="permalink"><a href="#module_err_http2_session_error" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_SESSION_ERROR</p>

</h3>
</div>

<p>The <code>Http2Session</code> closed with a non-zero error code.</p>
<p><a id="ERR_HTTP2_SOCKET_BOUND"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_socket_bound" id="module_err_http2_socket_bound"></a>
  <div class="permalink"><a href="#module_err_http2_socket_bound" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_SOCKET_BOUND</p>

</h3>
</div>

<p>An attempt was made to connect a <code>Http2Session</code> object to a <code>net.Socket</code> or
<code>tls.TLSSocket</code> that had already been bound to another <code>Http2Session</code> object.</p>
<p><a id="ERR_HTTP2_STATUS_101"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_status_101" id="module_err_http2_status_101"></a>
  <div class="permalink"><a href="#module_err_http2_status_101" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_STATUS_101</p>

</h3>
</div>

<p>Use of the <code>101</code> Informational status code is forbidden in HTTP/2.</p>
<p><a id="ERR_HTTP2_STATUS_INVALID"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_status_invalid" id="module_err_http2_status_invalid"></a>
  <div class="permalink"><a href="#module_err_http2_status_invalid" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_STATUS_INVALID</p>

</h3>
</div>

<p>An invalid HTTP status code has been specified. Status codes must be an integer
between <code>100</code> and <code>599</code> (inclusive).</p>
<p><a id="ERR_HTTP2_STREAM_CANCEL"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_stream_cancel" id="module_err_http2_stream_cancel"></a>
  <div class="permalink"><a href="#module_err_http2_stream_cancel" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_STREAM_CANCEL</p>

</h3>
</div>

<p>An <code>Http2Stream</code> was destroyed before any data was transmitted to the connected
peer.</p>
<p><a id="ERR_HTTP2_STREAM_ERROR"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_stream_error" id="module_err_http2_stream_error"></a>
  <div class="permalink"><a href="#module_err_http2_stream_error" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_STREAM_ERROR</p>

</h3>
</div>

<p>A non-zero error code was been specified in an <code>RST_STREAM</code> frame.</p>
<p><a id="ERR_HTTP2_STREAM_SELF_DEPENDENCY"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_stream_self_dependency" id="module_err_http2_stream_self_dependency"></a>
  <div class="permalink"><a href="#module_err_http2_stream_self_dependency" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_STREAM_SELF_DEPENDENCY</p>

</h3>
</div>

<p>When setting the priority for an HTTP/2 stream, the stream may be marked as
a dependency for a parent stream. This error code is used when an attempt is
made to mark a stream and dependent of itself.</p>
<p><a id="ERR_HTTP2_UNSUPPORTED_PROTOCOL"></a></p>


<div class="heading">
<h3>
  <a name="module_err_http2_unsupported_protocol" id="module_err_http2_unsupported_protocol"></a>
  <div class="permalink"><a href="#module_err_http2_unsupported_protocol" class="permalink fas fa-link"></a></div>
  <p>ERR_HTTP2_UNSUPPORTED_PROTOCOL</p>

</h3>
</div>

<p><code>http2.connect()</code> was passed a URL that uses any protocol other than <code>http:</code> or
<code>https:</code>.</p>
<p><a id="ERR_INDEX_OUT_OF_RANGE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_index_out_of_range" id="module_err_index_out_of_range"></a>
  <div class="permalink"><a href="#module_err_index_out_of_range" class="permalink fas fa-link"></a></div>
  <p>ERR_INDEX_OUT_OF_RANGE</p>

</h3>
</div>

<p>A given index was out of the accepted range (e.g. negative offsets).</p>
<p><a id="ERR_INSPECTOR_ALREADY_CONNECTED"></a></p>


<div class="heading">
<h3>
  <a name="module_err_inspector_already_connected" id="module_err_inspector_already_connected"></a>
  <div class="permalink"><a href="#module_err_inspector_already_connected" class="permalink fas fa-link"></a></div>
  <p>ERR_INSPECTOR_ALREADY_CONNECTED</p>

</h3>
</div>

<p>While using the <code>inspector</code> module, an attempt was made to connect when the
inspector was already connected.</p>
<p><a id="ERR_INSPECTOR_CLOSED"></a></p>


<div class="heading">
<h3>
  <a name="module_err_inspector_closed" id="module_err_inspector_closed"></a>
  <div class="permalink"><a href="#module_err_inspector_closed" class="permalink fas fa-link"></a></div>
  <p>ERR_INSPECTOR_CLOSED</p>

</h3>
</div>

<p>While using the <code>inspector</code> module, an attempt was made to use the inspector
after the session had already closed.</p>
<p><a id="ERR_INSPECTOR_NOT_AVAILABLE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_inspector_not_available" id="module_err_inspector_not_available"></a>
  <div class="permalink"><a href="#module_err_inspector_not_available" class="permalink fas fa-link"></a></div>
  <p>ERR_INSPECTOR_NOT_AVAILABLE</p>

</h3>
</div>

<p>The <code>inspector</code> module is not available for use.</p>
<p><a id="ERR_INSPECTOR_NOT_CONNECTED"></a></p>


<div class="heading">
<h3>
  <a name="module_err_inspector_not_connected" id="module_err_inspector_not_connected"></a>
  <div class="permalink"><a href="#module_err_inspector_not_connected" class="permalink fas fa-link"></a></div>
  <p>ERR_INSPECTOR_NOT_CONNECTED</p>

</h3>
</div>

<p>While using the <code>inspector</code> module, an attempt was made to use the inspector
before it was connected.</p>
<p><a id="ERR_INVALID_ARG_TYPE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_invalid_arg_type" id="module_err_invalid_arg_type"></a>
  <div class="permalink"><a href="#module_err_invalid_arg_type" class="permalink fas fa-link"></a></div>
  <p>ERR_INVALID_ARG_TYPE</p>

</h3>
</div>

<p>An argument of the wrong type was passed to a Node.js API.</p>
<p><a id="ERR_INVALID_ARG_VALUE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_invalid_arg_value" id="module_err_invalid_arg_value"></a>
  <div class="permalink"><a href="#module_err_invalid_arg_value" class="permalink fas fa-link"></a></div>
  <p>ERR_INVALID_ARG_VALUE</p>

</h3>
</div>

<p>An invalid or unsupported value was passed for a given argument.</p>
<p><a id="ERR_INVALID_ARRAY_LENGTH"></a></p>


<div class="heading">
<h3>
  <a name="module_err_invalid_array_length" id="module_err_invalid_array_length"></a>
  <div class="permalink"><a href="#module_err_invalid_array_length" class="permalink fas fa-link"></a></div>
  <p>ERR_INVALID_ARRAY_LENGTH</p>

</h3>
</div>

<p>An Array was not of the expected length or in a valid range.</p>
<p><a id="ERR_INVALID_ASYNC_ID"></a></p>


<div class="heading">
<h3>
  <a name="module_err_invalid_async_id" id="module_err_invalid_async_id"></a>
  <div class="permalink"><a href="#module_err_invalid_async_id" class="permalink fas fa-link"></a></div>
  <p>ERR_INVALID_ASYNC_ID</p>

</h3>
</div>

<p>An invalid <code>asyncId</code> or <code>triggerAsyncId</code> was passed using <code>AsyncHooks</code>. An id
less than -1 should never happen.</p>
<p><a id="ERR_INVALID_BUFFER_SIZE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_invalid_buffer_size" id="module_err_invalid_buffer_size"></a>
  <div class="permalink"><a href="#module_err_invalid_buffer_size" class="permalink fas fa-link"></a></div>
  <p>ERR_INVALID_BUFFER_SIZE</p>

</h3>
</div>

<p>A swap was performed on a <code>Buffer</code> but its size was not compatible with the
operation.</p>
<p><a id="ERR_INVALID_CALLBACK"></a></p>


<div class="heading">
<h3>
  <a name="module_err_invalid_callback" id="module_err_invalid_callback"></a>
  <div class="permalink"><a href="#module_err_invalid_callback" class="permalink fas fa-link"></a></div>
  <p>ERR_INVALID_CALLBACK</p>

</h3>
</div>

<p>A callback function was required but was not been provided to a Node.js API.</p>
<p><a id="ERR_INVALID_CHAR"></a></p>


<div class="heading">
<h3>
  <a name="module_err_invalid_char" id="module_err_invalid_char"></a>
  <div class="permalink"><a href="#module_err_invalid_char" class="permalink fas fa-link"></a></div>
  <p>ERR_INVALID_CHAR</p>

</h3>
</div>

<p>Invalid characters were detected in headers.</p>
<p><a id="ERR_INVALID_CURSOR_POS"></a></p>


<div class="heading">
<h3>
  <a name="module_err_invalid_cursor_pos" id="module_err_invalid_cursor_pos"></a>
  <div class="permalink"><a href="#module_err_invalid_cursor_pos" class="permalink fas fa-link"></a></div>
  <p>ERR_INVALID_CURSOR_POS</p>

</h3>
</div>

<p>A cursor on a given stream cannot be moved to a specified row without a
specified column.</p>
<p><a id="ERR_INVALID_DOMAIN_NAME"></a></p>


<div class="heading">
<h3>
  <a name="module_err_invalid_domain_name" id="module_err_invalid_domain_name"></a>
  <div class="permalink"><a href="#module_err_invalid_domain_name" class="permalink fas fa-link"></a></div>
  <p>ERR_INVALID_DOMAIN_NAME</p>

</h3>
</div>

<p><code>hostname</code> can not be parsed from a provided URL.</p>
<p><a id="ERR_INVALID_FD"></a></p>


<div class="heading">
<h3>
  <a name="module_err_invalid_fd" id="module_err_invalid_fd"></a>
  <div class="permalink"><a href="#module_err_invalid_fd" class="permalink fas fa-link"></a></div>
  <p>ERR_INVALID_FD</p>

</h3>
</div>

<p>A file descriptor (&#39;fd&#39;) was not valid (e.g. it was a negative value).</p>
<p><a id="ERR_INVALID_FD_TYPE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_invalid_fd_type" id="module_err_invalid_fd_type"></a>
  <div class="permalink"><a href="#module_err_invalid_fd_type" class="permalink fas fa-link"></a></div>
  <p>ERR_INVALID_FD_TYPE</p>

</h3>
</div>

<p>A file descriptor (&#39;fd&#39;) type was not valid.</p>
<p><a id="ERR_INVALID_FILE_URL_HOST"></a></p>


<div class="heading">
<h3>
  <a name="module_err_invalid_file_url_host" id="module_err_invalid_file_url_host"></a>
  <div class="permalink"><a href="#module_err_invalid_file_url_host" class="permalink fas fa-link"></a></div>
  <p>ERR_INVALID_FILE_URL_HOST</p>

</h3>
</div>

<p>A Node.js API that consumes <code>file:</code> URLs (such as certain functions in the
<a href="fs.html"><code>fs</code></a> module) encountered a file URL with an incompatible host. This
situation can only occur on Unix-like systems where only <code>localhost</code> or an empty
host is supported.</p>
<p><a id="ERR_INVALID_FILE_URL_PATH"></a></p>


<div class="heading">
<h3>
  <a name="module_err_invalid_file_url_path" id="module_err_invalid_file_url_path"></a>
  <div class="permalink"><a href="#module_err_invalid_file_url_path" class="permalink fas fa-link"></a></div>
  <p>ERR_INVALID_FILE_URL_PATH</p>

</h3>
</div>

<p>A Node.js API that consumes <code>file:</code> URLs (such as certain functions in the
<a href="fs.html"><code>fs</code></a> module) encountered a file URL with an incompatible path. The exact
semantics for determining whether a path can be used is platform-dependent.</p>
<p><a id="ERR_INVALID_HANDLE_TYPE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_invalid_handle_type" id="module_err_invalid_handle_type"></a>
  <div class="permalink"><a href="#module_err_invalid_handle_type" class="permalink fas fa-link"></a></div>
  <p>ERR_INVALID_HANDLE_TYPE</p>

</h3>
</div>

<p>An attempt was made to send an unsupported &quot;handle&quot; over an IPC communication
channel to a child process. See <a href="child_process.html#child_process_subprocess_send_message_sendhandle_options_callback"><code>subprocess.send()</code></a> and <a href="process.html#process_process_send_message_sendhandle_options_callback"><code>process.send()</code></a> for
more information.</p>
<p><a id="ERR_INVALID_HTTP_TOKEN"></a></p>


<div class="heading">
<h3>
  <a name="module_err_invalid_http_token" id="module_err_invalid_http_token"></a>
  <div class="permalink"><a href="#module_err_invalid_http_token" class="permalink fas fa-link"></a></div>
  <p>ERR_INVALID_HTTP_TOKEN</p>

</h3>
</div>

<p>An invalid HTTP token was supplied.</p>
<p><a id="ERR_INVALID_IP_ADDRESS"></a></p>


<div class="heading">
<h3>
  <a name="module_err_invalid_ip_address" id="module_err_invalid_ip_address"></a>
  <div class="permalink"><a href="#module_err_invalid_ip_address" class="permalink fas fa-link"></a></div>
  <p>ERR_INVALID_IP_ADDRESS</p>

</h3>
</div>

<p>An IP address is not valid.</p>
<p><a id="ERR_INVALID_OPT_VALUE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_invalid_opt_value" id="module_err_invalid_opt_value"></a>
  <div class="permalink"><a href="#module_err_invalid_opt_value" class="permalink fas fa-link"></a></div>
  <p>ERR_INVALID_OPT_VALUE</p>

</h3>
</div>

<p>An invalid or unexpected value was passed in an options object.</p>
<p><a id="ERR_INVALID_OPT_VALUE_ENCODING"></a></p>


<div class="heading">
<h3>
  <a name="module_err_invalid_opt_value_encoding" id="module_err_invalid_opt_value_encoding"></a>
  <div class="permalink"><a href="#module_err_invalid_opt_value_encoding" class="permalink fas fa-link"></a></div>
  <p>ERR_INVALID_OPT_VALUE_ENCODING</p>

</h3>
</div>

<p>An invalid or unknown file encoding was passed.</p>
<p><a id="ERR_INVALID_PERFORMANCE_MARK"></a></p>


<div class="heading">
<h3>
  <a name="module_err_invalid_performance_mark" id="module_err_invalid_performance_mark"></a>
  <div class="permalink"><a href="#module_err_invalid_performance_mark" class="permalink fas fa-link"></a></div>
  <p>ERR_INVALID_PERFORMANCE_MARK</p>

</h3>
</div>

<p>While using the Performance Timing API (<code>perf_hooks</code>), a performance mark is
invalid.</p>
<p><a id="ERR_INVALID_PROTOCOL"></a></p>


<div class="heading">
<h3>
  <a name="module_err_invalid_protocol" id="module_err_invalid_protocol"></a>
  <div class="permalink"><a href="#module_err_invalid_protocol" class="permalink fas fa-link"></a></div>
  <p>ERR_INVALID_PROTOCOL</p>

</h3>
</div>

<p>An invalid <code>options.protocol</code> was passed.</p>
<p><a id="ERR_INVALID_REPL_EVAL_CONFIG"></a></p>


<div class="heading">
<h3>
  <a name="module_err_invalid_repl_eval_config" id="module_err_invalid_repl_eval_config"></a>
  <div class="permalink"><a href="#module_err_invalid_repl_eval_config" class="permalink fas fa-link"></a></div>
  <p>ERR_INVALID_REPL_EVAL_CONFIG</p>

</h3>
</div>

<p>Both <code>breakEvalOnSigint</code> and <code>eval</code> options were set in the REPL config, which
is not supported.</p>
<p><a id="ERR_INVALID_SYNC_FORK_INPUT"></a></p>


<div class="heading">
<h3>
  <a name="module_err_invalid_sync_fork_input" id="module_err_invalid_sync_fork_input"></a>
  <div class="permalink"><a href="#module_err_invalid_sync_fork_input" class="permalink fas fa-link"></a></div>
  <p>ERR_INVALID_SYNC_FORK_INPUT</p>

</h3>
</div>

<p>A <code>Buffer</code>, <code>Uint8Array</code> or <code>string</code> was provided as stdio input to a
synchronous fork. See the documentation for the <a href="child_process.html"><code>child_process</code></a> module
for more information.</p>
<p><a id="ERR_INVALID_THIS"></a></p>


<div class="heading">
<h3>
  <a name="module_err_invalid_this" id="module_err_invalid_this"></a>
  <div class="permalink"><a href="#module_err_invalid_this" class="permalink fas fa-link"></a></div>
  <p>ERR_INVALID_THIS</p>

</h3>
</div>

<p>A Node.js API function was called with an incompatible <code>this</code> value.</p>
<p>Example:</p>
<pre class="prettyprint"><code class="lang-js">const { URLSearchParams } = require(&#39;url&#39;);
const urlSearchParams = new URLSearchParams(&#39;foo=bar&amp;baz=new&#39;);

const buf = Buffer.alloc(1);
urlSearchParams.has.call(buf, &#39;foo&#39;);
// Throws a TypeError with code &#39;ERR_INVALID_THIS&#39;
</code></pre>
<p><a id="ERR_INVALID_TUPLE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_invalid_tuple" id="module_err_invalid_tuple"></a>
  <div class="permalink"><a href="#module_err_invalid_tuple" class="permalink fas fa-link"></a></div>
  <p>ERR_INVALID_TUPLE</p>

</h3>
</div>

<p>An element in the <code>iterable</code> provided to the <a href="url.html#url_the_whatwg_url_api">WHATWG</a>
<a href="url.html#url_constructor_new_urlsearchparams_iterable"><code>URLSearchParams</code> constructor</a> did not
represent a <code>[name, value]</code> tuple – that is, if an element is not iterable, or
does not consist of exactly two elements.</p>
<p><a id="ERR_INVALID_URI"></a></p>


<div class="heading">
<h3>
  <a name="module_err_invalid_uri" id="module_err_invalid_uri"></a>
  <div class="permalink"><a href="#module_err_invalid_uri" class="permalink fas fa-link"></a></div>
  <p>ERR_INVALID_URI</p>

</h3>
</div>

<p>An invalid URI was passed.</p>
<p><a id="ERR_INVALID_URL"></a></p>


<div class="heading">
<h3>
  <a name="module_err_invalid_url" id="module_err_invalid_url"></a>
  <div class="permalink"><a href="#module_err_invalid_url" class="permalink fas fa-link"></a></div>
  <p>ERR_INVALID_URL</p>

</h3>
</div>

<p>An invalid URL was passed to the <a href="url.html#url_the_whatwg_url_api">WHATWG</a>
<a href="url.html#url_constructor_new_url_input_base"><code>URL</code> constructor</a> to be parsed. The thrown error object
typically has an additional property <code>&#39;input&#39;</code> that contains the URL that failed
to parse.</p>
<p><a id="ERR_INVALID_URL_SCHEME"></a></p>


<div class="heading">
<h3>
  <a name="module_err_invalid_url_scheme" id="module_err_invalid_url_scheme"></a>
  <div class="permalink"><a href="#module_err_invalid_url_scheme" class="permalink fas fa-link"></a></div>
  <p>ERR_INVALID_URL_SCHEME</p>

</h3>
</div>

<p>An attempt was made to use a URL of an incompatible scheme (protocol) for a
specific purpose. It is only used in the <a href="url.html#url_the_whatwg_url_api">WHATWG URL API</a> support in the
<a href="fs.html"><code>fs</code></a> module (which only accepts URLs with <code>&#39;file&#39;</code> scheme), but may be used
in other Node.js APIs as well in the future.</p>
<p><a id="ERR_IPC_CHANNEL_CLOSED"></a></p>


<div class="heading">
<h3>
  <a name="module_err_ipc_channel_closed" id="module_err_ipc_channel_closed"></a>
  <div class="permalink"><a href="#module_err_ipc_channel_closed" class="permalink fas fa-link"></a></div>
  <p>ERR_IPC_CHANNEL_CLOSED</p>

</h3>
</div>

<p>An attempt was made to use an IPC communication channel that was already closed.</p>
<p><a id="ERR_IPC_DISCONNECTED"></a></p>


<div class="heading">
<h3>
  <a name="module_err_ipc_disconnected" id="module_err_ipc_disconnected"></a>
  <div class="permalink"><a href="#module_err_ipc_disconnected" class="permalink fas fa-link"></a></div>
  <p>ERR_IPC_DISCONNECTED</p>

</h3>
</div>

<p>An attempt was made to disconnect an IPC communication channel that was already
disconnected. See the documentation for the <a href="child_process.html"><code>child_process</code></a> module
for more information.</p>
<p><a id="ERR_IPC_ONE_PIPE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_ipc_one_pipe" id="module_err_ipc_one_pipe"></a>
  <div class="permalink"><a href="#module_err_ipc_one_pipe" class="permalink fas fa-link"></a></div>
  <p>ERR_IPC_ONE_PIPE</p>

</h3>
</div>

<p>An attempt was made to create a child Node.js process using more than one IPC
communication channel. See the documentation for the <a href="child_process.html"><code>child_process</code></a> module
for more information.</p>
<p><a id="ERR_IPC_SYNC_FORK"></a></p>


<div class="heading">
<h3>
  <a name="module_err_ipc_sync_fork" id="module_err_ipc_sync_fork"></a>
  <div class="permalink"><a href="#module_err_ipc_sync_fork" class="permalink fas fa-link"></a></div>
  <p>ERR_IPC_SYNC_FORK</p>

</h3>
</div>

<p>An attempt was made to open an IPC communication channel with a synchronously
forked Node.js process. See the documentation for the <a href="child_process.html"><code>child_process</code></a> module
for more information.</p>
<p><a id="ERR_METHOD_NOT_IMPLEMENTED"></a></p>


<div class="heading">
<h3>
  <a name="module_err_method_not_implemented" id="module_err_method_not_implemented"></a>
  <div class="permalink"><a href="#module_err_method_not_implemented" class="permalink fas fa-link"></a></div>
  <p>ERR_METHOD_NOT_IMPLEMENTED</p>

</h3>
</div>

<p>A method is required but not implemented.</p>
<p><a id="ERR_MISSING_ARGS"></a></p>


<div class="heading">
<h3>
  <a name="module_err_missing_args" id="module_err_missing_args"></a>
  <div class="permalink"><a href="#module_err_missing_args" class="permalink fas fa-link"></a></div>
  <p>ERR_MISSING_ARGS</p>

</h3>
</div>

<p>A required argument of a Node.js API was not passed. This is only used for
strict compliance with the API specification (which in some cases may accept
<code>func(undefined)</code> but not <code>func()</code>). In most native Node.js APIs,
<code>func(undefined)</code> and <code>func()</code> are treated identically, and the
<a href="#ERR_INVALID_ARG_TYPE"><code>ERR_INVALID_ARG_TYPE</code></a> error code may be used instead.</p>
<p><a id="ERR_MISSING_DYNAMIC_INSTANTIATE_HOOK"></a></p>


<div class="heading">
<h3>
  <a name="module_err_missing_dynamic_instantiate_hook" id="module_err_missing_dynamic_instantiate_hook"></a>
  <div class="permalink"><a href="#module_err_missing_dynamic_instantiate_hook" class="permalink fas fa-link"></a></div>
  <p>ERR_MISSING_DYNAMIC_INSTANTIATE_HOOK</p>

</h3>
</div>

<p>An <a href="esm.html">ES6 module</a> loader hook specified <code>format: &#39;dynamic</code> but did not provide a
<code>dynamicInstantiate</code> hook.</p>
<p><a id="ERR_MISSING_MODULE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_missing_module" id="module_err_missing_module"></a>
  <div class="permalink"><a href="#module_err_missing_module" class="permalink fas fa-link"></a></div>
  <p>ERR_MISSING_MODULE</p>

</h3>
</div>

<p>An <a href="esm.html">ES6 module</a> could not be resolved.</p>
<p><a id="ERR_MODULE_RESOLUTION_LEGACY"></a></p>


<div class="heading">
<h3>
  <a name="module_err_module_resolution_legacy" id="module_err_module_resolution_legacy"></a>
  <div class="permalink"><a href="#module_err_module_resolution_legacy" class="permalink fas fa-link"></a></div>
  <p>ERR_MODULE_RESOLUTION_LEGACY</p>

</h3>
</div>

<p>A failure occurred resolving imports in an <a href="esm.html">ES6 module</a>.</p>
<p><a id="ERR_MULTIPLE_CALLBACK"></a></p>


<div class="heading">
<h3>
  <a name="module_err_multiple_callback" id="module_err_multiple_callback"></a>
  <div class="permalink"><a href="#module_err_multiple_callback" class="permalink fas fa-link"></a></div>
  <p>ERR_MULTIPLE_CALLBACK</p>

</h3>
</div>

<p>A callback was called more than once.</p>
<p><em>Note</em>: A callback is almost always meant to only be called once as the query
can either be fulfilled or rejected but not both at the same time. The latter
would be possible by calling a callback more than once.</p>
<p><a id="ERR_NAPI_CONS_FUNCTION"></a></p>


<div class="heading">
<h3>
  <a name="module_err_napi_cons_function" id="module_err_napi_cons_function"></a>
  <div class="permalink"><a href="#module_err_napi_cons_function" class="permalink fas fa-link"></a></div>
  <p>ERR_NAPI_CONS_FUNCTION</p>

</h3>
</div>

<p>While using <code>N-API</code>, a constructor passed was not a function.</p>
<p><a id="ERR_NAPI_CONS_PROTOTYPE_OBJECT"></a></p>


<div class="heading">
<h3>
  <a name="module_err_napi_cons_prototype_object" id="module_err_napi_cons_prototype_object"></a>
  <div class="permalink"><a href="#module_err_napi_cons_prototype_object" class="permalink fas fa-link"></a></div>
  <p>ERR_NAPI_CONS_PROTOTYPE_OBJECT</p>

</h3>
</div>

<p>While using <code>N-API</code>, <code>Constructor.prototype</code> was not an object.</p>
<p><a id="ERR_NAPI_INVALID_DATAVIEW_ARGS"></a></p>


<div class="heading">
<h3>
  <a name="module_err_napi_invalid_dataview_args" id="module_err_napi_invalid_dataview_args"></a>
  <div class="permalink"><a href="#module_err_napi_invalid_dataview_args" class="permalink fas fa-link"></a></div>
  <p>ERR_NAPI_INVALID_DATAVIEW_ARGS</p>

</h3>
</div>

<p>While calling <code>napi_create_dataview()</code>, a given <code>offset</code> was outside the bounds
of the dataview or <code>offset + length</code> was larger than a length of given <code>buffer</code>.</p>
<p><a id="ERR_NAPI_INVALID_TYPEDARRAY_ALIGNMENT"></a></p>


<div class="heading">
<h3>
  <a name="module_err_napi_invalid_typedarray_alignment" id="module_err_napi_invalid_typedarray_alignment"></a>
  <div class="permalink"><a href="#module_err_napi_invalid_typedarray_alignment" class="permalink fas fa-link"></a></div>
  <p>ERR_NAPI_INVALID_TYPEDARRAY_ALIGNMENT</p>

</h3>
</div>

<p>While calling <code>napi_create_typedarray()</code>, the provided <code>offset</code> was not a
multiple of the element size.</p>
<p><a id="ERR_NAPI_INVALID_TYPEDARRAY_LENGTH"></a></p>


<div class="heading">
<h3>
  <a name="module_err_napi_invalid_typedarray_length" id="module_err_napi_invalid_typedarray_length"></a>
  <div class="permalink"><a href="#module_err_napi_invalid_typedarray_length" class="permalink fas fa-link"></a></div>
  <p>ERR_NAPI_INVALID_TYPEDARRAY_LENGTH</p>

</h3>
</div>

<p>While calling <code>napi_create_typedarray()</code>, <code>(length * size_of_element) +
byte_offset</code> was larger than the length of given <code>buffer</code>.</p>
<p><a id="ERR_NO_CRYPTO"></a></p>


<div class="heading">
<h3>
  <a name="module_err_no_crypto" id="module_err_no_crypto"></a>
  <div class="permalink"><a href="#module_err_no_crypto" class="permalink fas fa-link"></a></div>
  <p>ERR_NO_CRYPTO</p>

</h3>
</div>

<p>An attempt was made to use crypto features while Node.js was not compiled with
OpenSSL crypto support.</p>
<p><a id="ERR_NO_ICU"></a></p>


<div class="heading">
<h3>
  <a name="module_err_no_icu" id="module_err_no_icu"></a>
  <div class="permalink"><a href="#module_err_no_icu" class="permalink fas fa-link"></a></div>
  <p>ERR_NO_ICU</p>

</h3>
</div>

<p>An attempt was made to use features that require <a href="intl.html#intl_options_for_building_node_js">ICU</a>, but Node.js was not
compiled with ICU support.</p>
<p><a id="ERR_NO_LONGER_SUPPORTED"></a></p>


<div class="heading">
<h3>
  <a name="module_err_no_longer_supported" id="module_err_no_longer_supported"></a>
  <div class="permalink"><a href="#module_err_no_longer_supported" class="permalink fas fa-link"></a></div>
  <p>ERR_NO_LONGER_SUPPORTED</p>

</h3>
</div>

<p>A Node.js API was called in an unsupported manner.</p>
<p>For example: <code>Buffer.write(string, encoding, offset[, length])</code></p>
<p><a id="ERR_OUT_OF_RANGE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_out_of_range" id="module_err_out_of_range"></a>
  <div class="permalink"><a href="#module_err_out_of_range" class="permalink fas fa-link"></a></div>
  <p>ERR_OUT_OF_RANGE</p>

</h3>
</div>

<p>An input argument value was outside an acceptable range.</p>
<p><a id="ERR_PARSE_HISTORY_DATA"></a></p>


<div class="heading">
<h3>
  <a name="module_err_parse_history_data" id="module_err_parse_history_data"></a>
  <div class="permalink"><a href="#module_err_parse_history_data" class="permalink fas fa-link"></a></div>
  <p>ERR_PARSE_HISTORY_DATA</p>

</h3>
</div>

<p>The <code>REPL</code> module was unable parse data from the REPL history file.</p>
<p><a id="ERR_REQUIRE_ESM"></a></p>


<div class="heading">
<h3>
  <a name="module_err_require_esm" id="module_err_require_esm"></a>
  <div class="permalink"><a href="#module_err_require_esm" class="permalink fas fa-link"></a></div>
  <p>ERR_REQUIRE_ESM</p>

</h3>
</div>

<p>An attempt was made to <code>require()</code> an <a href="esm.html">ES6 module</a>.</p>
<p><a id="ERR_SERVER_ALREADY_LISTEN"></a></p>


<div class="heading">
<h3>
  <a name="module_err_server_already_listen" id="module_err_server_already_listen"></a>
  <div class="permalink"><a href="#module_err_server_already_listen" class="permalink fas fa-link"></a></div>
  <p>ERR_SERVER_ALREADY_LISTEN</p>

</h3>
</div>

<p>The <a href="net.html#net_server_listen"><code>server.listen()</code></a> method was called while a <code>net.Server</code> was already
listening. This applies to all instances of <code>net.Server</code>, including HTTP, HTTPS,
and HTTP/2 Server instances.</p>
<p><a id="ERR_SOCKET_ALREADY_BOUND"></a></p>


<div class="heading">
<h3>
  <a name="module_err_socket_already_bound" id="module_err_socket_already_bound"></a>
  <div class="permalink"><a href="#module_err_socket_already_bound" class="permalink fas fa-link"></a></div>
  <p>ERR_SOCKET_ALREADY_BOUND</p>

</h3>
</div>

<p>An attempt was made to bind a socket that has already been bound.</p>
<p><a id="ERR_SOCKET_BAD_BUFFER_SIZE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_socket_bad_buffer_size" id="module_err_socket_bad_buffer_size"></a>
  <div class="permalink"><a href="#module_err_socket_bad_buffer_size" class="permalink fas fa-link"></a></div>
  <p>ERR_SOCKET_BAD_BUFFER_SIZE</p>

</h3>
</div>

<p>An invalid (negative) size was passed for either the <code>recvBufferSize</code> or
<code>sendBufferSize</code> options in <a href="#dgram_dgram_createsocket_options_callback"><code>dgram.createSocket()</code></a>.</p>
<p><a id="ERR_SOCKET_BAD_PORT"></a></p>


<div class="heading">
<h3>
  <a name="module_err_socket_bad_port" id="module_err_socket_bad_port"></a>
  <div class="permalink"><a href="#module_err_socket_bad_port" class="permalink fas fa-link"></a></div>
  <p>ERR_SOCKET_BAD_PORT</p>

</h3>
</div>

<p>An API function expecting a port &gt; 0 and &lt; 65536 received an invalid value.</p>
<p><a id="ERR_SOCKET_BAD_TYPE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_socket_bad_type" id="module_err_socket_bad_type"></a>
  <div class="permalink"><a href="#module_err_socket_bad_type" class="permalink fas fa-link"></a></div>
  <p>ERR_SOCKET_BAD_TYPE</p>

</h3>
</div>

<p>An API function expecting a socket type (<code>udp4</code> or <code>udp6</code>) received an invalid
value.</p>
<p><a id="ERR_SOCKET_BUFFER_SIZE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_socket_buffer_size" id="module_err_socket_buffer_size"></a>
  <div class="permalink"><a href="#module_err_socket_buffer_size" class="permalink fas fa-link"></a></div>
  <p>ERR_SOCKET_BUFFER_SIZE</p>

</h3>
</div>

<p>While using <a href="#dgram_dgram_createsocket_options_callback"><code>dgram.createSocket()</code></a>, the size of the receive or send <code>Buffer</code>
could not be determined.</p>
<p><a id="ERR_SOCKET_CANNOT_SEND"></a></p>


<div class="heading">
<h3>
  <a name="module_err_socket_cannot_send" id="module_err_socket_cannot_send"></a>
  <div class="permalink"><a href="#module_err_socket_cannot_send" class="permalink fas fa-link"></a></div>
  <p>ERR_SOCKET_CANNOT_SEND</p>

</h3>
</div>

<p>Data could be sent on a socket.</p>
<p><a id="ERR_SOCKET_CLOSED"></a></p>


<div class="heading">
<h3>
  <a name="module_err_socket_closed" id="module_err_socket_closed"></a>
  <div class="permalink"><a href="#module_err_socket_closed" class="permalink fas fa-link"></a></div>
  <p>ERR_SOCKET_CLOSED</p>

</h3>
</div>

<p>An attempt was made to operate on an already closed socket.</p>
<p><a id="ERR_SOCKET_DGRAM_NOT_RUNNING"></a></p>


<div class="heading">
<h3>
  <a name="module_err_socket_dgram_not_running" id="module_err_socket_dgram_not_running"></a>
  <div class="permalink"><a href="#module_err_socket_dgram_not_running" class="permalink fas fa-link"></a></div>
  <p>ERR_SOCKET_DGRAM_NOT_RUNNING</p>

</h3>
</div>

<p>A call was made and the UDP subsystem was not running.</p>
<p><a id="ERR_STDERR_CLOSE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_stderr_close" id="module_err_stderr_close"></a>
  <div class="permalink"><a href="#module_err_stderr_close" class="permalink fas fa-link"></a></div>
  <p>ERR_STDERR_CLOSE</p>

</h3>
</div>

<p>An attempt was made to close the <code>process.stderr</code> stream. By design, Node.js
does not allow <code>stdout</code> or <code>stderr</code> streams to be closed by user code.</p>
<p><a id="ERR_STDOUT_CLOSE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_stdout_close" id="module_err_stdout_close"></a>
  <div class="permalink"><a href="#module_err_stdout_close" class="permalink fas fa-link"></a></div>
  <p>ERR_STDOUT_CLOSE</p>

</h3>
</div>

<p>An attempt was made to close the <code>process.stdout</code> stream. By design, Node.js
does not allow <code>stdout</code> or <code>stderr</code> streams to be closed by user code.</p>
<p><a id="ERR_STREAM_CANNOT_PIPE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_stream_cannot_pipe" id="module_err_stream_cannot_pipe"></a>
  <div class="permalink"><a href="#module_err_stream_cannot_pipe" class="permalink fas fa-link"></a></div>
  <p>ERR_STREAM_CANNOT_PIPE</p>

</h3>
</div>

<p>An attempt was made to call <a href="#stream_readable_pipe_destination_options"><code>stream.pipe()</code></a> on a <a href="stream.html#stream_class_stream_writable"><code>Writable</code></a> stream.</p>
<p><a id="ERR_STREAM_NULL_VALUES"></a></p>


<div class="heading">
<h3>
  <a name="module_err_stream_null_values" id="module_err_stream_null_values"></a>
  <div class="permalink"><a href="#module_err_stream_null_values" class="permalink fas fa-link"></a></div>
  <p>ERR_STREAM_NULL_VALUES</p>

</h3>
</div>

<p>An attempt was made to call <a href="stream.html#stream_writable_write_chunk_encoding_callback"><code>stream.write()</code></a> with a <code>null</code> chunk.</p>
<p><a id="ERR_STREAM_PUSH_AFTER_EOF"></a></p>


<div class="heading">
<h3>
  <a name="module_err_stream_push_after_eof" id="module_err_stream_push_after_eof"></a>
  <div class="permalink"><a href="#module_err_stream_push_after_eof" class="permalink fas fa-link"></a></div>
  <p>ERR_STREAM_PUSH_AFTER_EOF</p>

</h3>
</div>

<p>An attempt was made to call <a href="stream.html#stream_readable_push_chunk_encoding"><code>stream.push()</code></a> after a <code>null</code>(EOF) had been
pushed to the stream.</p>
<p><a id="ERR_STREAM_READ_NOT_IMPLEMENTED"></a></p>


<div class="heading">
<h3>
  <a name="module_err_stream_read_not_implemented" id="module_err_stream_read_not_implemented"></a>
  <div class="permalink"><a href="#module_err_stream_read_not_implemented" class="permalink fas fa-link"></a></div>
  <p>ERR_STREAM_READ_NOT_IMPLEMENTED</p>

</h3>
</div>

<p>An attempt was made to use a readable stream that did not implement
<a href="stream.html#stream_readable_read_size_1"><code>readable._read()</code></a>.</p>
<p><a id="ERR_STREAM_UNSHIFT_AFTER_END_EVENT"></a></p>


<div class="heading">
<h3>
  <a name="module_err_stream_unshift_after_end_event" id="module_err_stream_unshift_after_end_event"></a>
  <div class="permalink"><a href="#module_err_stream_unshift_after_end_event" class="permalink fas fa-link"></a></div>
  <p>ERR_STREAM_UNSHIFT_AFTER_END_EVENT</p>

</h3>
</div>

<p>An attempt was made to call <a href="stream.html#stream_readable_unshift_chunk"><code>stream.unshift()</code></a> after the <code>end</code> event was
emitted.</p>
<p><a id="ERR_STREAM_WRAP"></a></p>


<div class="heading">
<h3>
  <a name="module_err_stream_wrap" id="module_err_stream_wrap"></a>
  <div class="permalink"><a href="#module_err_stream_wrap" class="permalink fas fa-link"></a></div>
  <p>ERR_STREAM_WRAP</p>

</h3>
</div>

<p>Prevents an abort if a string decoder was set on the Socket or if the decoder
is in <code>objectMode</code>.</p>
<p>Example</p>
<pre class="prettyprint"><code class="lang-js">const Socket = require(&#39;net&#39;).Socket;
const instance = new Socket();

instance.setEncoding(&#39;utf8&#39;);
</code></pre>
<p><a id="ERR_STREAM_WRITE_AFTER_END"></a></p>


<div class="heading">
<h3>
  <a name="module_err_stream_write_after_end" id="module_err_stream_write_after_end"></a>
  <div class="permalink"><a href="#module_err_stream_write_after_end" class="permalink fas fa-link"></a></div>
  <p>ERR_STREAM_WRITE_AFTER_END</p>

</h3>
</div>

<p>An attempt was made to call <a href="stream.html#stream_writable_write_chunk_encoding_callback"><code>stream.write()</code></a> after <code>stream.end()</code> has been
called.</p>
<p><a id="ERR_TLS_CERT_ALTNAME_INVALID"></a></p>


<div class="heading">
<h3>
  <a name="module_err_tls_cert_altname_invalid" id="module_err_tls_cert_altname_invalid"></a>
  <div class="permalink"><a href="#module_err_tls_cert_altname_invalid" class="permalink fas fa-link"></a></div>
  <p>ERR_TLS_CERT_ALTNAME_INVALID</p>

</h3>
</div>

<p>While using TLS, the hostname/IP of the peer did not match any of the
subjectAltNames in its certificate.</p>
<p><a id="ERR_TLS_DH_PARAM_SIZE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_tls_dh_param_size" id="module_err_tls_dh_param_size"></a>
  <div class="permalink"><a href="#module_err_tls_dh_param_size" class="permalink fas fa-link"></a></div>
  <p>ERR_TLS_DH_PARAM_SIZE</p>

</h3>
</div>

<p>While using TLS, the parameter offered for the Diffie-Hellman (<code>DH</code>)
key-agreement protocol is too small. By default, the key length must be greater
than or equal to 1024 bits to avoid vulnerabilities, even though it is strongly
recommended to use 2048 bits or larger for stronger security.</p>
<p><a id="ERR_TLS_HANDSHAKE_TIMEOUT"></a></p>


<div class="heading">
<h3>
  <a name="module_err_tls_handshake_timeout" id="module_err_tls_handshake_timeout"></a>
  <div class="permalink"><a href="#module_err_tls_handshake_timeout" class="permalink fas fa-link"></a></div>
  <p>ERR_TLS_HANDSHAKE_TIMEOUT</p>

</h3>
</div>

<p>A TLS/SSL handshake timed out. In this case, the server must also abort the
connection.</p>
<p><a id="ERR_TLS_RENEGOTIATION_FAILED"></a></p>


<div class="heading">
<h3>
  <a name="module_err_tls_renegotiation_failed" id="module_err_tls_renegotiation_failed"></a>
  <div class="permalink"><a href="#module_err_tls_renegotiation_failed" class="permalink fas fa-link"></a></div>
  <p>ERR_TLS_RENEGOTIATION_FAILED</p>

</h3>
</div>

<p>A TLS renegotiation request has failed in a non-specific way.</p>
<p><a id="ERR_TLS_REQUIRED_SERVER_NAME"></a></p>


<div class="heading">
<h3>
  <a name="module_err_tls_required_server_name" id="module_err_tls_required_server_name"></a>
  <div class="permalink"><a href="#module_err_tls_required_server_name" class="permalink fas fa-link"></a></div>
  <p>ERR_TLS_REQUIRED_SERVER_NAME</p>

</h3>
</div>

<p>While using TLS, the <code>server.addContext()</code> method was called without providing
a hostname in the first parameter.</p>
<p><a id="ERR_TLS_SESSION_ATTACK"></a></p>


<div class="heading">
<h3>
  <a name="module_err_tls_session_attack" id="module_err_tls_session_attack"></a>
  <div class="permalink"><a href="#module_err_tls_session_attack" class="permalink fas fa-link"></a></div>
  <p>ERR_TLS_SESSION_ATTACK</p>

</h3>
</div>

<p>An excessive amount of TLS renegotiations is detected, which is a potential
vector for denial-of-service attacks.</p>
<p><a id="ERR_TRANSFORM_ALREADY_TRANSFORMING"></a></p>


<div class="heading">
<h3>
  <a name="module_err_transform_already_transforming" id="module_err_transform_already_transforming"></a>
  <div class="permalink"><a href="#module_err_transform_already_transforming" class="permalink fas fa-link"></a></div>
  <p>ERR_TRANSFORM_ALREADY_TRANSFORMING</p>

</h3>
</div>

<p>A Transform stream finished while it was still transforming.</p>
<p><a id="ERR_TRANSFORM_WITH_LENGTH_0"></a></p>


<div class="heading">
<h3>
  <a name="module_err_transform_with_length_0" id="module_err_transform_with_length_0"></a>
  <div class="permalink"><a href="#module_err_transform_with_length_0" class="permalink fas fa-link"></a></div>
  <p>ERR_TRANSFORM_WITH_LENGTH_0</p>

</h3>
</div>

<p>A Transform stream finished with data still in the write buffer.</p>
<p><a id="ERR_UNCAUGHT_EXCEPTION_CAPTURE_ALREADY_SET"></a></p>


<div class="heading">
<h3>
  <a name="module_err_uncaught_exception_capture_already_set" id="module_err_uncaught_exception_capture_already_set"></a>
  <div class="permalink"><a href="#module_err_uncaught_exception_capture_already_set" class="permalink fas fa-link"></a></div>
  <p>ERR_UNCAUGHT_EXCEPTION_CAPTURE_ALREADY_SET</p>

</h3>
</div>

<p><a href="process.html#process_process_setuncaughtexceptioncapturecallback_fn"><code>process.setUncaughtExceptionCaptureCallback()</code></a> was called twice,
without first resetting the callback to <code>null</code>.</p>
<p>This error is designed to prevent accidentally overwriting a callback registered
from another module.</p>
<p><a id="ERR_UNESCAPED_CHARACTERS"></a></p>


<div class="heading">
<h3>
  <a name="module_err_unescaped_characters" id="module_err_unescaped_characters"></a>
  <div class="permalink"><a href="#module_err_unescaped_characters" class="permalink fas fa-link"></a></div>
  <p>ERR_UNESCAPED_CHARACTERS</p>

</h3>
</div>

<p>A string that contained unescaped characters was received.</p>
<p><a id="ERR_UNHANDLED_ERROR"></a></p>


<div class="heading">
<h3>
  <a name="module_err_unhandled_error" id="module_err_unhandled_error"></a>
  <div class="permalink"><a href="#module_err_unhandled_error" class="permalink fas fa-link"></a></div>
  <p>ERR_UNHANDLED_ERROR</p>

</h3>
</div>

<p>An unhandled error occurred (for instance, when an <code>&#39;error&#39;</code> event is emitted
by an <a href="events.html"><code>EventEmitter</code></a> but an <code>&#39;error&#39;</code> handler is not registered).</p>
<p><a id="ERR_UNKNOWN_ENCODING"></a></p>


<div class="heading">
<h3>
  <a name="module_err_unknown_encoding" id="module_err_unknown_encoding"></a>
  <div class="permalink"><a href="#module_err_unknown_encoding" class="permalink fas fa-link"></a></div>
  <p>ERR_UNKNOWN_ENCODING</p>

</h3>
</div>

<p>An invalid or unknown encoding option was passed to an API.</p>
<p><a id="ERR_UNKNOWN_FILE_EXTENSION"></a></p>


<div class="heading">
<h3>
  <a name="module_err_unknown_file_extension" id="module_err_unknown_file_extension"></a>
  <div class="permalink"><a href="#module_err_unknown_file_extension" class="permalink fas fa-link"></a></div>
  <p>ERR_UNKNOWN_FILE_EXTENSION</p>

</h3>
</div>

<p>An attempt was made to load a module with an unknown or unsupported file
extension.</p>
<p><a id="ERR_UNKNOWN_MODULE_FORMAT"></a></p>


<div class="heading">
<h3>
  <a name="module_err_unknown_module_format" id="module_err_unknown_module_format"></a>
  <div class="permalink"><a href="#module_err_unknown_module_format" class="permalink fas fa-link"></a></div>
  <p>ERR_UNKNOWN_MODULE_FORMAT</p>

</h3>
</div>

<p>An attempt was made to load a module with an unknown or unsupported format.</p>
<p><a id="ERR_UNKNOWN_SIGNAL"></a></p>


<div class="heading">
<h3>
  <a name="module_err_unknown_signal" id="module_err_unknown_signal"></a>
  <div class="permalink"><a href="#module_err_unknown_signal" class="permalink fas fa-link"></a></div>
  <p>ERR_UNKNOWN_SIGNAL</p>

</h3>
</div>

<p>An invalid or unknown process signal was passed to an API expecting a valid
signal (such as <a href="child_process.html#child_process_subprocess_kill_signal"><code>subprocess.kill()</code></a>).</p>
<p><a id="ERR_UNKNOWN_STDIN_TYPE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_unknown_stdin_type" id="module_err_unknown_stdin_type"></a>
  <div class="permalink"><a href="#module_err_unknown_stdin_type" class="permalink fas fa-link"></a></div>
  <p>ERR_UNKNOWN_STDIN_TYPE</p>

</h3>
</div>

<p>An attempt was made to launch a Node.js process with an unknown <code>stdin</code> file
type. This error is usually an indication of a bug within Node.js itself,
although it is possible for user code to trigger it.</p>
<p><a id="ERR_UNKNOWN_STREAM_TYPE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_unknown_stream_type" id="module_err_unknown_stream_type"></a>
  <div class="permalink"><a href="#module_err_unknown_stream_type" class="permalink fas fa-link"></a></div>
  <p>ERR_UNKNOWN_STREAM_TYPE</p>

</h3>
</div>

<p>An attempt was made to launch a Node.js process with an unknown <code>stdout</code> or
<code>stderr</code> file type. This error is usually an indication of a bug within Node.js
itself, although it is possible for user code to trigger it.</p>
<p><a id="ERR_V8BREAKITERATOR"></a></p>


<div class="heading">
<h3>
  <a name="module_err_v8breakiterator" id="module_err_v8breakiterator"></a>
  <div class="permalink"><a href="#module_err_v8breakiterator" class="permalink fas fa-link"></a></div>
  <p>ERR_V8BREAKITERATOR</p>

</h3>
</div>

<p>The V8 BreakIterator API was used but the full ICU data set is not installed.</p>
<p><a id="ERR_VALID_PERFORMANCE_ENTRY_TYPE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_valid_performance_entry_type" id="module_err_valid_performance_entry_type"></a>
  <div class="permalink"><a href="#module_err_valid_performance_entry_type" class="permalink fas fa-link"></a></div>
  <p>ERR_VALID_PERFORMANCE_ENTRY_TYPE</p>

</h3>
</div>

<p>While using the Performance Timing API (<code>perf_hooks</code>), no valid performance
entry types were found.</p>
<p><a id="ERR_VALUE_OUT_OF_RANGE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_value_out_of_range" id="module_err_value_out_of_range"></a>
  <div class="permalink"><a href="#module_err_value_out_of_range" class="permalink fas fa-link"></a></div>
  <p>ERR_VALUE_OUT_OF_RANGE</p>

</h3>
</div>

<p>A given value is out of the accepted range.</p>
<p><a id="ERR_VM_MODULE_ALREADY_LINKED"></a></p>


<div class="heading">
<h3>
  <a name="module_err_vm_module_already_linked" id="module_err_vm_module_already_linked"></a>
  <div class="permalink"><a href="#module_err_vm_module_already_linked" class="permalink fas fa-link"></a></div>
  <p>ERR_VM_MODULE_ALREADY_LINKED</p>

</h3>
</div>

<p>The module attempted to be linked is not eligible for linking, because of one of
the following reasons:</p>
<ul>
<li>It has already been linked (<code>linkingStatus</code> is <code>&#39;linked&#39;</code>)</li>
<li>It is being linked (<code>linkingStatus</code> is <code>&#39;linking&#39;</code>)</li>
<li>Linking has failed for this module (<code>linkingStatus</code> is <code>&#39;errored&#39;</code>)</li>
</ul>
<p><a id="ERR_VM_MODULE_DIFFERENT_CONTEXT"></a></p>


<div class="heading">
<h3>
  <a name="module_err_vm_module_different_context" id="module_err_vm_module_different_context"></a>
  <div class="permalink"><a href="#module_err_vm_module_different_context" class="permalink fas fa-link"></a></div>
  <p>ERR_VM_MODULE_DIFFERENT_CONTEXT</p>

</h3>
</div>

<p>The module being returned from the linker function is from a different context
than the parent module. Linked modules must share the same context.</p>
<p><a id="ERR_VM_MODULE_LINKING_ERRORED"></a></p>


<div class="heading">
<h3>
  <a name="module_err_vm_module_linking_errored" id="module_err_vm_module_linking_errored"></a>
  <div class="permalink"><a href="#module_err_vm_module_linking_errored" class="permalink fas fa-link"></a></div>
  <p>ERR_VM_MODULE_LINKING_ERRORED</p>

</h3>
</div>

<p>The linker function returned a module for which linking has failed.</p>
<p><a id="ERR_VM_MODULE_NOT_LINKED"></a></p>


<div class="heading">
<h3>
  <a name="module_err_vm_module_not_linked" id="module_err_vm_module_not_linked"></a>
  <div class="permalink"><a href="#module_err_vm_module_not_linked" class="permalink fas fa-link"></a></div>
  <p>ERR_VM_MODULE_NOT_LINKED</p>

</h3>
</div>

<p>The module must be successfully linked before instantiation.</p>
<p><a id="ERR_VM_MODULE_NOT_MODULE"></a></p>


<div class="heading">
<h3>
  <a name="module_err_vm_module_not_module" id="module_err_vm_module_not_module"></a>
  <div class="permalink"><a href="#module_err_vm_module_not_module" class="permalink fas fa-link"></a></div>
  <p>ERR_VM_MODULE_NOT_MODULE</p>

</h3>
</div>

<p>The fulfilled value of a linking promise is not a <code>vm.Module</code> object.</p>
<p><a id="ERR_VM_MODULE_STATUS"></a></p>


<div class="heading">
<h3>
  <a name="module_err_vm_module_status" id="module_err_vm_module_status"></a>
  <div class="permalink"><a href="#module_err_vm_module_status" class="permalink fas fa-link"></a></div>
  <p>ERR_VM_MODULE_STATUS</p>

</h3>
</div>

<p>The current module&#39;s status does not allow for this operation. The specific
meaning of the error depends on the specific function.</p>
<p><a id="ERR_ZLIB_BINDING_CLOSED"></a></p>


<div class="heading">
<h3>
  <a name="module_err_zlib_binding_closed" id="module_err_zlib_binding_closed"></a>
  <div class="permalink"><a href="#module_err_zlib_binding_closed" class="permalink fas fa-link"></a></div>
  <p>ERR_ZLIB_BINDING_CLOSED</p>

</h3>
</div>

<p>An attempt was made to use a <code>zlib</code> object after it has already been closed.</p>
<p><a id="ERR_ZLIB_INITIALIZATION_FAILED"></a></p>


<div class="heading">
<h3>
  <a name="module_err_zlib_initialization_failed" id="module_err_zlib_initialization_failed"></a>
  <div class="permalink"><a href="#module_err_zlib_initialization_failed" class="permalink fas fa-link"></a></div>
  <p>ERR_ZLIB_INITIALIZATION_FAILED</p>

</h3>
</div>

<p><p>Creation of a <a href="zlib.html"><code>zlib</code></a> object failed due to incorrect configuration.</p>
<!-- [end-include:errors.md] -->
<!-- [start-include:events.md] --></p>

<div class='expandable-header' id='class_Error-expand'>
<div class="heading">
    <h2>
        <a name="class_Error" id="class_Error"></a>
        <i class='expandable-icon fas fa-caret-right' id="class_Error-expand-icon"></i>
        <div class="permalink"><a href="#class_Error" class="permalink fas fa-link"></a></div>
        <p>Class: Error</p>

    </h2>
</div>

</div>
<div class='expandable-content' id='class_Error-expand-content'>
<p>A generic JavaScript <code>Error</code> object that does not denote any specific
circumstance of why the error occurred. <code>Error</code> objects capture a &quot;stack trace&quot;
detailing the point in the code at which the <code>Error</code> was instantiated, and may
provide a text description of the error.</p>
<p>For crypto only, <code>Error</code> objects will include the OpenSSL error stack in a
separate property called <code>opensslErrorStack</code> if it is available when the error
is thrown.</p>
<p>All errors generated by Node.js, including all System and JavaScript errors,
will either be instances of, or inherit from, the <code>Error</code> class.</p>


<div class="heading">
<h3>
  <a name="subgroup_class_Error_Properties" id="subgroup_class_Error_Properties"></a>
  <div class="permalink"><a href="#subgroup_class_Error_Properties" class="permalink fas fa-link"></a></div>
  <p>Properties</p>

</h3>
</div>


<div class='expandable-header' id='property_stackTraceLimit-expand'>
<div class="heading">
    <h4>
        <a name="property_stackTraceLimit" id="property_stackTraceLimit"></a>
        <i class='expandable-icon fas fa-caret-right' id="property_stackTraceLimit-expand-icon"></i>
        <div class="permalink"><a href="#property_stackTraceLimit" class="permalink fas fa-link"></a></div>
        <p><code>stackTraceLimit</code> {number} </p>

    </h4>
</div>

</div>
<div class='expandable-content' id='property_stackTraceLimit-expand-content'>
<p>The <code>Error.stackTraceLimit</code> property specifies the number of stack frames
collected by a stack trace (whether generated by <code>new Error().stack</code> or
<code>Error.captureStackTrace(obj)</code>).</p>
<p>The default value is <code>10</code> but may be set to any valid JavaScript number. Changes
will affect any stack trace captured <em>after</em> the value has been changed.</p>
<p>If set to a non-number value, or set to a negative number, stack traces will
not capture any frames.</p>


</div><div class='expandable-header' id='property_code_1-expand'>
<div class="heading">
    <h4>
        <a name="property_code_1" id="property_code_1"></a>
        <i class='expandable-icon fas fa-caret-right' id="property_code_1-expand-icon"></i>
        <div class="permalink"><a href="#property_code_1" class="permalink fas fa-link"></a></div>
        <p><code>code</code> {string} </p>

    </h4>
</div>

</div>
<div class='expandable-content' id='property_code_1-expand-content'>
<p>The <code>error.code</code> property is a string label that identifies the kind of error.
See <a href="#nodejs-error-codes">Node.js Error Codes</a> for details about specific codes.</p>


</div><div class='expandable-header' id='property_message-expand'>
<div class="heading">
    <h4>
        <a name="property_message" id="property_message"></a>
        <i class='expandable-icon fas fa-caret-right' id="property_message-expand-icon"></i>
        <div class="permalink"><a href="#property_message" class="permalink fas fa-link"></a></div>
        <p><code>message</code> {string} </p>

    </h4>
</div>

</div>
<div class='expandable-content' id='property_message-expand-content'>
<p><p>The <code>error.message</code> property is the string description of the error as set by
calling <code>new Error(message)</code>. The <code>message</code> passed to the constructor will also
appear in the first line of the stack trace of the <code>Error</code>, however changing
this property after the <code>Error</code> object is created <em>may not</em> change the first
line of the stack trace (for example, when <code>error.stack</code> is read before this
property is changed).</p></p>
<pre class="prettyprint"><code class="lang-js">const err = new Error(&#39;The message&#39;);
console.error(err.message);
// Prints: The message
</code></pre>


</div><div class='expandable-header' id='property_stack-expand'>
<div class="heading">
    <h4>
        <a name="property_stack" id="property_stack"></a>
        <i class='expandable-icon fas fa-caret-right' id="property_stack-expand-icon"></i>
        <div class="permalink"><a href="#property_stack" class="permalink fas fa-link"></a></div>
        <p><code>stack</code> {string} </p>

    </h4>
</div>

</div>
<div class='expandable-content' id='property_stack-expand-content'>
<p>The <code>error.stack</code> property is a string describing the point in the code at which
the <code>Error</code> was instantiated.</p>
<p>For example:</p>
<pre class="prettyprint"><code class="lang-txt">Error: Things keep happening!
   at /home/gbusey/file.js:525:2
   at Frobnicator.refrobulate (/home/gbusey/business-logic.js:424:21)
   at Actor.&lt;anonymous&gt; (/home/gbusey/actors.js:400:8)
   at increaseSynergy (/home/gbusey/actors.js:701:6)
</code></pre>
<p>The first line is formatted as <code>&lt;error class name&gt;: &lt;error message&gt;</code>, and
is followed by a series of stack frames (each line beginning with &quot;at &quot;).
Each frame describes a call site within the code that lead to the error being
generated. V8 attempts to display a name for each function (by variable name,
function name, or object method name), but occasionally it will not be able to
find a suitable name. If V8 cannot determine a name for the function, only
location information will be displayed for that frame. Otherwise, the
determined function name will be displayed with location information appended
in parentheses.</p>
<p>Frames are only generated for JavaScript functions. If, for example, execution
synchronously passes through a C++ addon function called <code>cheetahify</code> which
itself calls a JavaScript function, the frame representing the <code>cheetahify</code> call
will not be present in the stack traces:</p>
<pre class="prettyprint"><code class="lang-js">const cheetahify = require(&#39;./native-binding.node&#39;);

function makeFaster() {
  // cheetahify <em>synchronously</em> calls speedy.
  cheetahify(function speedy() {
    throw new Error(&#39;oh no!&#39;);
  });
}

makeFaster();
// will throw:
//   /home/gbusey/file.js:6
//       throw new Error(&#39;oh no!&#39;);
//           ^
//   Error: oh no!
//       at speedy (/home/gbusey/file.js:6:11)
//       at makeFaster (/home/gbusey/file.js:5:3)
//       at Object.&lt;anonymous&gt; (/home/gbusey/file.js:10:1)
//       at Module._compile (module.js:456:26)
//       at Object.Module._extensions..js (module.js:474:10)
//       at Module.load (module.js:356:32)
//       at Function.Module._load (module.js:312:12)
//       at Function.Module.runMain (module.js:497:10)
//       at startup (node.js:119:16)
//       at node.js:906:3
</code></pre>
<p>The location information will be one of:</p>
<ul>
<li><code>native</code>, if the frame represents a call internal to V8 (as in <code>[].forEach</code>).</li>
<li><code>plain-filename.js:line:column</code>, if the frame represents a call internal
 to Node.js.</li>
<li><code>/absolute/path/to/file.js:line:column</code>, if the frame represents a call in
a user program, or its dependencies.</li>
</ul>
<p>The string representing the stack trace is lazily generated when the
<code>error.stack</code> property is <strong>accessed</strong>.</p>
<p>The number of frames captured by the stack trace is bounded by the smaller of
<code>Error.stackTraceLimit</code> or the number of available frames on the current event
loop tick.</p>
<p>System-level errors are generated as augmented <code>Error</code> instances, which are
detailed <a href="#errors_system_errors">here</a>.</p>


</div>
<div class="heading">
<h3>
  <a name="subgroup_class_Error_Methods" id="subgroup_class_Error_Methods"></a>
  <div class="permalink"><a href="#subgroup_class_Error_Methods" class="permalink fas fa-link"></a></div>
  <p>Methods</p>

</h3>
</div>


<div class='expandable-header' id='method_captureStackTrace-expand'>
<div class="heading">
    <h4>
        <a name="method_captureStackTrace" id="method_captureStackTrace"></a>
        <i class='expandable-icon fas fa-caret-right' id="method_captureStackTrace-expand-icon"></i>
        <div class="permalink"><a href="#method_captureStackTrace" class="permalink fas fa-link"></a></div>
        <p>Error.captureStackTrace(targetObject[, constructorOpt])</p>

    </h4>
</div>

</div>
<div class='expandable-content' id='method_captureStackTrace-expand-content'>
<p><p>Creates a <code>.stack</code> property on <code>targetObject</code>, which when accessed returns
a string representing the location in the code at which
<code>Error.captureStackTrace()</code> was called.</p></p>
<pre class="prettyprint"><code class="lang-js">const myObject = {};
Error.captureStackTrace(myObject);
myObject.stack;  // similar to `new Error().stack`
</code></pre>
<p>The first line of the trace will be prefixed with <code>${myObject.name}: ${myObject.message}</code>.</p>
<p>The optional <code>constructorOpt</code> argument accepts a function. If given, all frames
above <code>constructorOpt</code>, including <code>constructorOpt</code>, will be omitted from the
generated stack trace.</p>
<p>The <code>constructorOpt</code> argument is useful for hiding implementation
details of error generation from an end user. For instance:</p>
<pre class="prettyprint"><code class="lang-js">function MyError() {
  Error.captureStackTrace(this, MyError);
}

// Without passing MyError to captureStackTrace, the MyError
// frame would show up in the .stack property. By passing
// the constructor, we omit that frame, and retain all frames below it.
new MyError().stack;
</code></pre>


</div>
</div><div class='expandable-header' id='class_AssertionError-expand'>
<div class="heading">
    <h2>
        <a name="class_AssertionError" id="class_AssertionError"></a>
        <i class='expandable-icon fas fa-caret-right' id="class_AssertionError-expand-icon"></i>
        <div class="permalink"><a href="#class_AssertionError" class="permalink fas fa-link"></a></div>
        <p>Class: AssertionError</p>

    </h2>
</div>

</div>
<div class='expandable-content' id='class_AssertionError-expand-content'>
<p><p>A subclass of <code>Error</code> that indicates the failure of an assertion. Such errors
commonly indicate inequality of actual and expected value.</p></p>
<p><p>For example:</p></p>
<pre class="prettyprint"><code class="lang-js">assert.strictEqual(1, 2);
// AssertionError [ERR_ASSERTION]: 1 === 2
</code></pre>


</div><div class='expandable-header' id='class_RangeError-expand'>
<div class="heading">
    <h2>
        <a name="class_RangeError" id="class_RangeError"></a>
        <i class='expandable-icon fas fa-caret-right' id="class_RangeError-expand-icon"></i>
        <div class="permalink"><a href="#class_RangeError" class="permalink fas fa-link"></a></div>
        <p>Class: RangeError</p>

    </h2>
</div>

</div>
<div class='expandable-content' id='class_RangeError-expand-content'>
<p>A subclass of <code>Error</code> that indicates that a provided argument was not within the
set or range of acceptable values for a function; whether that is a numeric
range, or outside the set of options for a given function parameter.</p>
<p>For example:</p>
<pre class="prettyprint"><code class="lang-js">require(&#39;net&#39;).connect(-1);
// throws &quot;RangeError: &quot;port&quot; option should be &gt;= 0 and &lt; 65536: -1&quot;
</code></pre>
<p>Node.js will generate and throw <code>RangeError</code> instances <em>immediately</em> as a form
of argument validation.</p>


</div><div class='expandable-header' id='class_ReferenceError-expand'>
<div class="heading">
    <h2>
        <a name="class_ReferenceError" id="class_ReferenceError"></a>
        <i class='expandable-icon fas fa-caret-right' id="class_ReferenceError-expand-icon"></i>
        <div class="permalink"><a href="#class_ReferenceError" class="permalink fas fa-link"></a></div>
        <p>Class: ReferenceError</p>

    </h2>
</div>

</div>
<div class='expandable-content' id='class_ReferenceError-expand-content'>
<p>A subclass of <code>Error</code> that indicates that an attempt is being made to access a
variable that is not defined. Such errors commonly indicate typos in code, or
an otherwise broken program.</p>
<p>While client code may generate and propagate these errors, in practice, only V8
will do so.</p>
<pre class="prettyprint"><code class="lang-js">doesNotExist;
// throws ReferenceError, doesNotExist is not a variable in this program.
</code></pre>
<p>Unless an application is dynamically generating and running code,
<code>ReferenceError</code> instances should always be considered a bug in the code
or its dependencies.</p>


</div><div class='expandable-header' id='class_SyntaxError-expand'>
<div class="heading">
    <h2>
        <a name="class_SyntaxError" id="class_SyntaxError"></a>
        <i class='expandable-icon fas fa-caret-right' id="class_SyntaxError-expand-icon"></i>
        <div class="permalink"><a href="#class_SyntaxError" class="permalink fas fa-link"></a></div>
        <p>Class: SyntaxError</p>

    </h2>
</div>

</div>
<div class='expandable-content' id='class_SyntaxError-expand-content'>
<p>A subclass of <code>Error</code> that indicates that a program is not valid JavaScript.
These errors may only be generated and propagated as a result of code
evaluation. Code evaluation may happen as a result of <code>eval</code>, <code>Function</code>,
<code>require</code>, or <a href="vm.html">vm</a>. These errors are almost always indicative of a broken
program.</p>
<pre class="prettyprint"><code class="lang-js">try {
  require(&#39;vm&#39;).runInThisContext(&#39;binary ! isNotOk&#39;);
} catch (err) {
  // err will be a SyntaxError
}
</code></pre>
<p><code>SyntaxError</code> instances are unrecoverable in the context that created them –
they may only be caught by other contexts.</p>


</div><div class='expandable-header' id='class_TypeError-expand'>
<div class="heading">
    <h2>
        <a name="class_TypeError" id="class_TypeError"></a>
        <i class='expandable-icon fas fa-caret-right' id="class_TypeError-expand-icon"></i>
        <div class="permalink"><a href="#class_TypeError" class="permalink fas fa-link"></a></div>
        <p>Class: TypeError</p>

    </h2>
</div>

</div>
<div class='expandable-content' id='class_TypeError-expand-content'>
<p>A subclass of <code>Error</code> that indicates that a provided argument is not an
allowable type. For example, passing a function to a parameter which expects a
string would be considered a TypeError.</p>
<pre class="prettyprint"><code class="lang-js">require(&#39;url&#39;).parse(() =&gt; { });
// throws TypeError, since it expected a string
</code></pre>
<p>Node.js will generate and throw <code>TypeError</code> instances <em>immediately</em> as a form
of argument validation.</p>


</div>

  <div class="footer">
    <p>Some footer text. Optional. Copyright &copy; whenever by your bidness.</p>
    <p>Dubbed by <img src="images/mixtape.png" title="Dubbed by mixtape." style="width:40px;position:relative;top:8px"></img> mixtape.</p>
  </div>

  </div>
  </body>
</html>